### ISSUE TITLE
Add content for learn section

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1000]

**Comment by counterweightoperator** [comment]
@HenrikJannsen I can take point on this one.

Do you think it's better to share the proposed content:
- Directly as a PR changing the texts in the codebase itself, or...
- First in some other format, like some markdown files, and then afterwards we add it to the codebase?

**Comment by HenrikJannsen** [comment]
Its fine to make a PR directly. I can give feedback in the PR and we can update it if needed.

**Comment by counterweightoperator** [comment]
I've finished a first shot of this in PR #1095. 

I think more improvements could be made in terms of adding some visuals and adding links to external resources that could be helpful for newbies, but maybe we can just get this in as a first version and iterate in further PRs when needed.
