### ISSUE TITLE
Add Bisq 2 section to webpage and add download links

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1033]
See https://github.com/bisq-network/bisq-website/issues/475

**Comment by HenrikJannsen** [comment]
Rough suggestion for a minimal page:

<img width="1250" alt="bisq2-webpage" src="https://github.com/bisq-network/bisq2/assets/116298498/57f0f3a6-5f33-4a94-87d3-02f808da0e62">

**Comment by HenrikJannsen** [comment]
@counterweightoperator Would you be available for that?

**Comment by counterweightoperator** [comment]
Definition of done is simply to grab the mock and implement it as a static page? Or are we planning 

Also, I'm not very familiar with web front-end development. I wouldn't shy away of giving it a shot, but if there's any tool/environment which is adequate to work on this, I would appreciate the info.

**Comment by HenrikJannsen** [comment]
Yes to get the mock into the webpage would be enough. The video is not part of the task.
I am also not much familiar with the web stack we use. Maybe best to ask in the Bisq1 dev/Bisq2 dev rooms in Matrix.

**Comment by RyanHotchkiss** [comment]
Hello! I've been visiting in the Bisq forum and mentioned that I have writing/editing, SEO & marketing skills and data, analytics & trends experience. I also have front-end development – HTML, CSS, PHP, & JS, – so I could make the changes required on the front end. 

I was hoping I might be able to contribute to Bisq, increase it's visibility and fandom.

**Comment by HenrikJannsen** [comment]
@RyanHotchkiss That task is already taken by @counterweightoperator (I forget to assign it). But feel free to join the Bisq matrix channels and get in touch with contributors there to see where you could contribute.

**Comment by RyanHotchkiss** [comment]
They're the ones who suggested this task! Is there a place where I can find a list of open tasks?

**Comment by HenrikJannsen** [comment]
https://github.com/bisq-network/bisq2/issues

**Comment by HenrikJannsen** [comment]
@counterweightoperator How is the state of that issue?

**Comment by HenrikJannsen** [comment]
We want to add a Bisq2 video as well. You can prepare whats needed for that.

**Comment by salokiam** [comment]
### Here is the current stats. Asking for review, especially the text.
![image](https://github.com/bisq-network/bisq2/assets/99251513/ce2e2e0e-968c-46d7-b669-bb19bda502ef)

**Comment by leo816** [comment]
Great job @salokiam .
It seems like exactly what we were asking for. 
Instead of the first image I would include the initial video guide or a screenshot of the BUY and SELL window which looks simple and clean.

**Comment by HenrikJannsen** [comment]
@salokiam Thanks for the implementation!

Some comments:
- Maybe we should move the top navigation item one position right after "Getting started"? Or rename "Getting started" to something else (Bisq 1 overview...). Another option would be to add a new landing page with 2 options to choose from: Bisq 1 for experienced traders, Bisq2 (Bisq Easy) for newbies. But that would be a separate effort and can be deployed later. Maybe @pedromvpg has some suggestions for that.
- "Trade apps" have been renamed to "Trade protocols"
- At the 2nd notes: Maybe add the flexibility in regards to tx fees (e.g. users can use LN for BTC settlement), so it might be also attractive for seasoned Bisq users beside the seller use case.
- Where is "Getting started" at the end linked to?

**Comment by salokiam** [comment]
> Great job @salokiam . It seems like exactly what we were asking for. Instead of the first image I would include the initial video guide or a screenshot of the BUY and SELL window which looks simple and clean.

thanks. Yes,I think so too, we dont need a screenshot and the video.

**Comment by salokiam** [comment]
What about translating the page into different languages? I have no experience with how that works and who is doing the translations.

**Comment by salokiam** [comment]
Here is the latest changes, please see

1. Menue has entry 'Bisq1 Start' renamed from 'Getting Started', this may need translation
2. Menue Bis2 is now one position to thr right.
3. Video has replaced the screenshot. the screenshot is removed.
4. Bisq Easy section has now a hint about Lightning and fow transaction fees.
5. The Homepage ('/') has no mention of Bisq 2 to have a gradual start of Bisq 2. We may add more visibility over time.

![image](https://github.com/bisq-network/bisq2/assets/99251513/bb6fc398-b1ca-4880-9990-1881714bf44f)

**Comment by HenrikJannsen** [comment]
I think the important work is done and we only need to add the video once available. I will close the issue here.
