### ISSUE TITLE
Improve network info screen

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1041]
Adopt screen to new design and UI elements

**Comment by aspire2dev** [comment]
I volunteer for this task

**Comment by aspire2dev** [comment]
Submitting the code now... This is my suggestion for the Network Info screen. (I left clearnet and tor running to be able to show how it maps with more than one protocol, as we expect tor and i2p in production)

![image](https://github.com/bisq-network/bisq2/assets/143408636/64a1241c-ea9a-4018-bf8d-b1cd3b342cfb)

**Comment by aspire2dev** [comment]
@HenrikJannsen , I think we can close this issue, no?
