### ISSUE TITLE
Check if OS notifications work correctly on Windows and Linux

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1071]

**Comment by aspire2dev** [comment]
I volunteer for this task

**Comment by djing-chan** [comment]
I will check if notifications are correct when using a Linux binary (Ubuntu)

**Comment by djing-chan** [comment]
Fixed a bug in https://github.com/bisq-network/bisq2/pull/1359 and confirm that with that PR the notification icon is displayed on Ubuntu. For Linux system where ``notify-send` is not supported, it is not tested. It should fall back to AwtNotifications.
