### ISSUE TITLE
Handle case if no market price is available

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1160]
The create and take offer screens depend on an available market price. 
We should support also the case that no market price is available. This might be problematic as certain checks like max/min fiat amounts might not work.
Alternative would be that we do not allow to create or take an offer if market price is not there, but that would represent a serious dependency on the market price providers.

**Comment by HenrikJannsen** [comment]
There are also issues in the trade process when the peer was offline. At startup it can take a bit until the market price is available. if the trade mailbox messages are processed faster than the market price is available, we can get failed trades.

**Comment by namloan** [comment]
Taking a look at this one

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/bisq2/discussions/1275

**Comment by HenrikJannsen** [comment]
I think with https://github.com/bisq-network/bisq2/pull/1355 the cases with no market data can be ignored as exceptional.
