### ISSUE TITLE
Investigate error message of potential UI bug

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1166]
I get sometimes that error message in the logs without any visible problem.

```
javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class 
javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; 
javafx.scene.paint.Paint is in unnamed module of loader 'app')' while converting value for 
'-fx-background-color' from rule '*.bisq-dark-bg' in stylesheet resources/css/containers.css
```

Would be good to find out the reason for that and to fix it.

**Comment by aspire2dev** [comment]
I was able to reproduce the issue.. It happens when go through the User Options, reputation section. If I click on the buttons (Signed account age witness, account age, ...) randomly around 3 times, I get the error.
I'll work on this issue.

**Comment by aspire2dev** [comment]
Steps to reproduce:

1. Go to user options
2. Select reputation tab
3. Click on signed account age witness , next, next, close
4. Click on account age, next, next, close
5. Re-open account age witness and the error should appear

**Comment by aspire2dev** [comment]
Seems related to https://bugs.openjdk.org/browse/JDK-8268657 (not fixed) and https://bugs.openjdk.org/browse/JDK-8291853

**Comment by HenrikJannsen** [comment]
Ok. Will close it.
