### ISSUE TITLE
Improve completed screen at the trade process

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1186]
The completed screen could need more love...

**Comment by axpoems** [comment]
Following up with my last PR (on the Bisq Easy waiting states icons), I think I have some spare love to work on  this.

**Comment by HenrikJannsen** [comment]
See discussion at https://github.com/bisq-network/bisq2/pull/1349#issuecomment-1804920684

**Comment by axpoems** [comment]
From discussion at #1349

I've created these mock-ups for the final step of the trade process for both seller and buyer.

**For the seller:**


![mock 2 seller](https://github.com/bisq-network/bisq2/assets/145597137/8bae3c98-1991-419d-91c7-6ab8e4708af7)


**For the buyer:**


![mock 2 buyer](https://github.com/bisq-network/bisq2/assets/145597137/844df834-4b7d-4f85-9f53-adf37c94eeb3)

@HenrikJannsen 
What do you think? Is there any parameter that is missing or in excess in the panels?

**Comment by HenrikJannsen** [comment]
Looks great! Is it intended to be shown only on the right side or over the whole available width (hiding the left stepper box)?

**Comment by axpoems** [comment]
> Looks great! Is it intended to be shown only on the right side or over the whole available width (hiding the left stepper box)?

The idea is the latter.

**Comment by HenrikJannsen** [comment]
> Is there any parameter that is missing or in excess in the panels?

Maybe instead the fees we could show how long the trade took?
Or show the real amount of the minerfee (we could get that from the tx - but could be done later).

We would like to add a feedback feature. Only to the peer as we dont know how to do that decentralized/secure. But I think it would be still nice to have the option to send and receive feedback from the peer (some simple with stars and a text msg and maybe some emoticons). But can be delegated for later as well.

**Comment by axpoems** [comment]
> Maybe instead the fees we could show how long the trade took?

Yes that could be included. Why do you think this is important?

<br>

> Or show the real amount of the minerfee (we could get that from the tx - but could be done later).

You mean in the buyer? I thought the buyer wouldn't care for a fee that he didn't pay, but could be included as well.

<br>

> We would like to add a feedback feature. Only to the peer as we dont know how to do that decentralized/secure. But I think it would be still nice to have the option to send and receive feedback from the peer (some simple with stars and a text msg and maybe some emoticons). But can be delegated for later as well.

To the peer do you mean to the buyer?
I like this idea; however, implementing the feedback feature would require a redesign of the screen. My suggestion is to include a 'send feedback' button. Clicking on this button would lead the user to a new screen where, as you suggested, he can rate with stars and include a brief text message.

**Comment by HenrikJannsen** [comment]
> Why do you think this is important?

I think the trade duration is an important factor, but not sure how important. To keep all to the minimum is maybe better. We should avoid information overload.

> You mean in the buyer? I thought the buyer wouldn't care for a fee that he didn't pay, but could be included as well.

For both, but true for the buyer its less important and the seller will know it anyway. Again maybe better to keep all to the minimum.

> To the peer do you mean to the buyer?

Both sides. Yes was meant as button which shows a new screen/popup for giving feedback. But I think that can be delegated for post-launch.
