### ISSUE TITLE
Refactor and clean up css/styles and standardize styles in app

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1211]
- cleanup and generalize css (atm lot of duplicates, changes not adopted to style names,...)
- get a set of styles we want to use and apply them to all screens. atm there might be small differences in font size/weight,...
- adjust all images/icons to the set of colors we use. the current green gets an update. the greys are not consistently applies
- standardize the hover/pressed/disabled states of buttons and related controls
- improve styles (some fonts are to small, less readible,..)
- improve or renew icons which do not have a good quality (some icons got derived from screenshots and do not have proper transparancy)
- organize the image directory better (got messed up over time)

**Comment by axpoems** [comment]
I will start working on this.

**Comment by HenrikJannsen** [comment]
I guess we can close that. It is an ongoing effort but I guess large parts are already improved.
