### ISSUE TITLE
Fix layout issue in Dashboard

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1214]
If there are diff. number of lines the height if the box is different and the 2 buttons are not aligned.
 
<img width="1009" alt="Screenshot 2023-09-21 at 00 48 53" src="https://github.com/bisq-network/bisq2/assets/116298498/692628eb-306a-4713-9032-85ef1989b2b7">

Here we use a gridpane inside to avoid that problem. Same container structure should be applied to the Dashboard small boxes.

<img width="1126" alt="Screenshot 2023-09-21 at 00 49 05" src="https://github.com/bisq-network/bisq2/assets/116298498/1e1f8c5a-7590-451b-8557-9feaae393292">

**Comment by aspire2dev** [comment]
I volunteer for this task
