### ISSUE TITLE
Improve chat guide content and layout

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1215]
Headline is too small and content need to be reviewed/improved and layout adjusted so its more readable.
<img width="1508" alt="Screenshot 2023-09-21 at 00 59 27" src="https://github.com/bisq-network/bisq2/assets/116298498/8294d22e-0749-4aeb-a0e3-172ddc3dc57a">

**Comment by aspire2dev** [comment]
I volunteer for this task.

**Comment by aspire2dev** [comment]
How does this look as a first draft? I moved the close button to the upper right and changed it's style to a cross close button. Increased in 0.1em the size of the headline and changed the list to an ordered list. The text was also reviewed.
![image](https://github.com/bisq-network/bisq2/assets/143408636/5f84dae6-e061-455c-ab85-1bbb096910a2)

**Comment by HenrikJannsen** [comment]
Not sure if an ordered list is better here. For one the 10 breaks the alignment and the items are not in a particular order, thus applying numbers feels not right to me.

**Comment by aspire2dev** [comment]
> Not sure if an ordered list is better here. For one the 10 breaks the alignment and the items are not in a particular order, thus applying numbers feels not right to me.

Updated removing the ordered list.

![image](https://github.com/bisq-network/bisq2/assets/143408636/24ba7cbe-1984-4ffa-82cb-34b17ec243b5)
