### ISSUE TITLE
Consider to add a transition animation also at tab views

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1216]
Changing between tab views do not apply the transition animation.
We could add it there as well but with a faster animation time so that switching tabs is not getting too slow.
Not sure if needed or even better.

**Comment by aspire2dev** [comment]
I can work on this one.

**Comment by aspire2dev** [comment]
What are your thoughts? This animation was recorded with the duration divided by 8.
https://github.com/bisq-network/bisq2/assets/143408636/fcd7549b-ed00-4468-91ab-7e4b12d4b59e

**Comment by aspire2dev** [comment]
What are your thoughts? This animation was recorded with the duration divided by 10.

https://github.com/bisq-network/bisq2/assets/143408636/bc81bd2d-8446-4517-a15f-c0c299adc90e

**Comment by HenrikJannsen** [comment]
Looks good to me. I assume its the same animation used in the normal view transitions
