### ISSUE TITLE
Test mediation use case

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1217]
There might be open issues when a trade enters mediation.

**Comment by DrColver** [comment]
@HenrikJannsen Is there some documentation on how to set up a mediator in dev environment?

**Comment by HenrikJannsen** [comment]
You need multiple nodes for the whole infrastructure:
- Bisq 1 user app (for registering mediator and oracle)
- Bitcoin core in regtest
- Bisq 1 DAO node
- Bisq 2 oracle node (bisq.oracle_node_app.OracleNodeApp)
- Bisq 2 user app


All bonded roles in bisq 2 need to be registered as DAO bonded roles. Only seed nodes and oracle nodes not (would be a chicken and egg problem), but for manual verification we also provide the data and those nodes should follow the same process.

In bisq 1 make a compensation request for the oracle and mediator (or any of the other bonded roles). After the vote period is over (you create the regtest blocks) you go to the bonded roles screen and use the profile id for creating a signature which you will use then in bisq 2 to send to the oracle node which will verify it via the Bisq 1 DAO node (rest API).
There are instructions in the bonded roles screen.

Here are the prog args for Bisq 1 DAO node I used:
--useLocalhostForP2P=true --useDevPrivilegeKeys=true --baseCurrencyNetwork=BTC_REGTEST --nodePort=8081 --appName=bisq-BTC_REGTEST_dao_node_8082 --fullDaoNode=true --rpcUser=bisq --rpcPassword=bisq --rpcPort=18443 --rpcBlockNotificationPort=5122 --daoNodeApiUrl=http://localhost --daoNodeApiPort=8082

The oracle node needs a key pair. In `DevMode` are the keypairs for dev testing. 


bisq2_OracleNode1:
-Dapplication.appName=bisq2_OracleNode1
-Dapplication.network.defaultNodePortByTransportType.clear=9000
-Dapplication.network.supportedTransportTypes.2=CLEAR
-Dapplication.network.seedAddressByTransportType.clear.0=127.0.0.1:8000
-Dapplication.network.seedAddressByTransportType.clear.1=127.0.0.1:8001
-Dapplication.oracleNode.privateKey=[PRIV KEY from DevMode]
-Dapplication.oracleNode.publicKey=[PUB KEY from DevMode]
-Dapplication.oracleNode.ignoreSecurityManager=false
-Dapplication.oracleNode.profileId=[you profile ID]
-Dapplication.oracleNode.bondUserName=[bisq 1 mediator username]
-Dapplication.oracleNode.signatureBase64=IMMVri9oJktDvcF7qmNJSVuY/cdd9yd1RUuNds84ckBYZddZ85ri8ASZohYa6uckBHIawo0S7/jyZQJduRf5weA=
-Dapplication.oracleNode.keyId=Oracle_node_1_52b8104000a034200041
-Dapplication.oracleNode.staticPublicKeysProvided=true
-Dapplication.bondedRoles.ignoreSecurityManager=true

The profileId and keyId I guess are logged, so you need to start once to see it.
bondUserName: I used bisq_2_oracle_operator_1, need to be the same as the username registered the mediator in bisq 1
signatureBase64: i think that is the signature of the oracle node registered as dao node in bisq1. i think its only for informational purpose (manual verification) and you could use any nonempty string or register a oracle node in bisq1. I think the bisq 1 bond username is missing here and should be added as well to make the manual verification process more accurate.

I hope thats all, otherwise ping me in matrix (might not be so much online atm).

If all works, would be great if you can make a dev doc out of it.

**Comment by HenrikJannsen** [comment]
See also https://github.com/bisq-network/bisq2/discussions/952 for general overview / discussion.
Not all realized as in that discussion doc. But should give an idea about the goals and concept.

**Comment by HenrikJannsen** [comment]
I will have a look into it...

**Comment by DrColver** [comment]
@HenrikJannsen I have finally managed to register a mediator. The latest oracle code on main doesn't work. There is a problem with the NetworkId initialization. I think it has to do with the refactoring around that part of the code. It only worked for me with an older commit from bisq2 (using 2a07cdf) and with the latest daonode for bisq1.
