### ISSUE TITLE
Make sure that important text fields are not truncated

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1218]
When scaling the app down to min. size some labels/textfields are truncated (e.g. header of tabviews).
We need to ensure that the important fields get not truncated. Using min width would be easiest but has the drawback that it does not support diff. sizes with translates strings. Better to use hBox growth ALWAYS if possible or other means. But if too complicated minWidth is better than nothing, if small part is truncated its acceptable as well. Also there will be tabs truncated and we need to make the trade off what to truncate. We could also hide the tab headline when its too small width.

**Comment by aspire2dev** [comment]
I volunteer for this task
