### ISSUE TITLE
Add overlay to chat messages

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#122]
At a chat message entry we add on rollover an overlay similar like in Element/Keybase. 
Items:
- React with emoji (keep last 3 used emojis in a row)
- Reply
- Open private channel (if not my message)
- Edit (if my message)
- Delete (if my message)
- More options ("...")

At click on More options we show an overlay with:
- Copy message
- Copy link to message
- Ignore user (if not my message)
- Report user to moderator (if not my message)

Keybase:
<img width="310" alt="Screenshot 2022-03-18 at 16 36 17" src="https://user-images.githubusercontent.com/54558767/159034405-341d3df9-78da-44b8-a246-2da6bcd79fa3.png">

Element:
<img width="197" alt="Screenshot 2022-03-18 at 16 41 31" src="https://user-images.githubusercontent.com/54558767/159034984-68012ef6-81fb-400b-8b65-7f4ff2205170.png">

<img width="297" alt="Screenshot 2022-03-18 at 16 29 28" src="https://user-images.githubusercontent.com/54558767/159034421-ca1d5c4d-54e3-41af-9ece-1ad89a085b29.png">

**Comment by chimp1984** [comment]
Reply feature is implemented in #141

**Comment by chimp1984** [comment]
Edit and delete are implemented but deleting after a restart fails atm.

@salokiam You can use the send private message button (method is in controller but empty atm) for opening a PM.

**Comment by chimp1984** [comment]
@xyzmaker123 Interested on that?

At that issue the overlay is still missing.
If we support Emoji is bit open and depends on another issue, so best to keep that part out for now.
But the more options overlay with the mentioned actions would be good to get in.
There is the bisq.desktop.overlay.PopOver which can be used as base for it. Might require a custom component with some adoptions. Design-wise we need to get some suggestion from Pedro but we can do it so that it fits current design.

**Comment by xyzmaker123** [comment]
Sure @chimp1984 - I can take this topic
