### ISSUE TITLE
Smaller view sizes break buttons on User Options view

### ISSUE THREAD

**Issue by aspire2dev** [bisq-network/bisq2#1246]
Button text doesn't wrap at the following tabs within User options:

Reputation:
![image](https://github.com/bisq-network/bisq2/assets/143408636/e4c4a800-5319-46e3-a5e4-9f1b3c4673d9)

Nodes
![image](https://github.com/bisq-network/bisq2/assets/143408636/3217fe85-b717-400f-bd90-0236edd69454)

**Comment by djing-chan** [comment]
There is quite a lot of left and right padding. We could reduce the padding in case the text gets truncated. Additionally a minWidth can be applied.

**Comment by aspire2dev** [comment]
I can work on this one, as this is pretty similar to 1265

**Comment by aspire2dev** [comment]
I did wrap the button text and made sure all buttons have the same height. Some of the texts are very large and wouldn't fit even with the padding.
What are your thoughts?
![image](https://github.com/bisq-network/bisq2/assets/143408636/05862934-94e6-4afa-9e71-b0f48ac09f68)

![image](https://github.com/bisq-network/bisq2/assets/143408636/7f6a5f23-a2f8-48ff-b204-2fb9145239b3)

When the window is larger and the button fits in one line, it automatically resizes into one line again.
![image](https://github.com/bisq-network/bisq2/assets/143408636/59972ef3-e695-43bf-8c7b-5c999385a1ff)
