### ISSUE TITLE
Fix UI bugs with reputation screen and popup

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1265]
The buttons should not get truncated.

<img width="717" alt="Screenshot 2023-10-15 at 17 34 54" src="https://github.com/bisq-network/bisq2/assets/116298498/fe498358-ec9b-47a6-9245-d9de68bdff07">

And the popup use a too large width:
<img width="1486" alt="Screenshot 2023-10-15 at 17 35 12" src="https://github.com/bisq-network/bisq2/assets/116298498/38b3173b-25bd-4fa3-b9c7-45f1b42d5cc6">

**Comment by aspire2dev** [comment]
I'll take a look at this one

**Comment by HenrikJannsen** [comment]
Fixed in https://github.com/bisq-network/bisq2/pull/1401
