### ISSUE TITLE
Add notification badge to trade item in open trades list view

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1266]
If there are multiple trades it is not clear which trade triggered the notification. We should add the badge to the trade row.
<img width="1431" alt="Screenshot 2023-10-15 at 17 45 56" src="https://github.com/bisq-network/bisq2/assets/116298498/a2cc065c-fe06-4a9c-8d9b-6d21713ac8bc">

**Comment by djing-chan** [comment]
I am working on that.
![Screenshot](https://github.com/bisq-network/bisq2/assets/146422224/fdd11ac5-2ab4-4d7c-8686-b12f53d5551c)
