### ISSUE TITLE
Consider using the same orange color for trade notification badge instead of red

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1267]
I think it would be better to use the same color for the badge as used for the notification pane.

<img width="1451" alt="Screenshot 2023-10-15 at 17 48 57" src="https://github.com/bisq-network/bisq2/assets/116298498/715b6d9a-c11b-4456-8c00-35ad94802bbd">

**Comment by djing-chan** [comment]
I can work on that

**Comment by djing-chan** [comment]
Looks like that:
![Screenshot from 2023-10-24 12-18-28](https://github.com/bisq-network/bisq2/assets/146422224/b5d4af18-8d71-404a-831f-4bcf34175a5e)
