### ISSUE TITLE
Use text instead of a badge in market drop down menu

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1268]
Use text instead of the badge as its not clear what the number means and currently the tooltip is not working. E.g. having "23 offers" right aligned in a HBox with the left aligned text of the market.

<img width="584" alt="Screenshot 2023-10-15 at 17 50 28" src="https://github.com/bisq-network/bisq2/assets/116298498/98ed56c1-3ad3-478d-9975-4602ac4ebc05">

**Comment by djing-chan** [comment]
I can work on that

**Comment by djing-chan** [comment]
Implemented in https://github.com/bisq-network/bisq2/pull/1299
