### ISSUE TITLE
Chat is broken

### ISSUE THREAD

**Issue by namloan** [bisq-network/bisq2#1293]
Messages in the offerbook aren't refreshed when switching channels + the last message is duplicated when going back to the original channel.

This happens since commit [Add icons to chat messages to show delivery status](https://github.com/bisq-network/bisq2/commit/de74109cb8cff65ebca94764c9a77d28d5ac4164).

@djing-chan will you be able to take a look?

**Comment by djing-chan** [comment]
Thanks for reporting. I will have a look into it.

**Comment by djing-chan** [comment]
Here is the fix: https://github.com/bisq-network/bisq2/pull/1297

**Comment by namloan** [comment]
@djing-chan awesome, thanks a lot!
