### ISSUE TITLE
Add filter to channels

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#130]
Add a filter to a channel to only display messages matching the filter criteria.

Criteria:
- Search string
- Show BUY offers
- Show SELL offers
- Maybe more options to filter for offer properties (payment method, amounts,...). But maybe not needed for now.

**Comment by xyzmaker123** [comment]
Do we have UI designs for it, or developer should propose something?

**Comment by chimp1984** [comment]
Sorry I started working on that already as part of https://github.com/bisq-network/bisq2/issues/132
