### ISSUE TITLE
Improve trade cancellation use case

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1316]
If a trade gets cancelled we should display it very clearly to the user (at the moment it is only a "Peer left" chat message).
We also should block the trade protocol to proceed so that the non-cancelling peer does not continue with the trade.

There are different stages for cancelling a trade:
- Abandon/reject trade (before the seller has sent their payment data). Traders can abandon or reject a trade. Abandon is used for the taker and reject used for the maker.
- Cancel trade: after seller has sent payment data. It is a breach of the trade rule to cancel a trade without clear reason or in agreement with the peer.
- Leave trade: after the payment has been completed but the user might have not moved to the complete screen (in case the explorer lookup has failed the user need to manually confirm that trade is completed)

We can add new transitions to the protocol which handle the 3 different events.

Abandon trade (same as reject):
Source states are those before sellers payment data got exchanged.
Target state is a final state `ABANDONED`

Cancel trade:
Source states are those after seller sent payment data but before completed state.
Target state is the final state `CANCELLED`

Leave trade:
After btc confirmed and before completed.
Target state is the final state `PEER_LEFT`.

Not sure if it makes sense to model the leave trade case in the protocol.

In case of the cancel events we should show the state in the left protocol steps as alternative to completed and maybe in a different color (yellow?)

**Comment by djing-chan** [comment]
I can work on that
