### ISSUE TITLE
Switching tabs fast makes content empty

### ISSUE THREAD

**Issue by namloan** [bisq-network/bisq2#1319]
![switch_tabs_fast](https://github.com/bisq-network/bisq2/assets/138292162/eb3c9dab-aaab-439b-8f55-e36ba3c524b0)

**Comment by HenrikJannsen** [comment]
Can I assign you @namloan ?

**Comment by namloan** [comment]
@HenrikJannsen leave it unassigned for now, I'd like to first close the things I have already assigned: https://github.com/bisq-network/bisq2/issues/883 and https://github.com/bisq-network/bisq2/issues/1160 . So this should be free for anyone to pick - I suspect this may be a good first issue as well.

**Comment by namloan** [comment]
Can't reproduce anymore after the latest updates that made the transitions faster.
