### ISSUE TITLE
Mouseover at edit chat message buggy

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1325]
When doing a mouse over at the cancel or save button at edit offer/msg the lower part of the buttons do not get the mouse event. Seems there is some hidden invisible UI element (prob the toolbar box) covering it and not have mouseTransparency set when set invisible. To use managed there was problematic with layout, but would be a better approach if not too much effort.

**Comment by namloan** [comment]
Couldn't reproduce, is this still an issue?

**Comment by HenrikJannsen** [comment]
Also cannot reproduce it anymore. Seems to be fixed.
