### ISSUE TITLE
Background of quote message same as list view background

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1326]
The background color of the quote should be different to the other background.
As it is part of the new message sent maybe the same background as the input textfield box might be an idea.

<img width="1131" alt="Screenshot 2023-11-05 at 13 17 41" src="https://github.com/bisq-network/bisq2/assets/116298498/6a146322-7ccd-496e-b94b-5e42148c59be">

**Comment by axpoems** [comment]
Thank you for pointing it out. I am doing a full review of the grey backgrounds, will come back with some corrections, including this one. You can assign this to me.
