### ISSUE TITLE
Add switch to close BisqEasy offers of type "Buyer as a Maker" once they have been taken

### ISSUE THREAD

**Issue by mrblue313** [bisq-network/bisq2#1344]
At the moment, when an offer is published it remains open until the user closes it and thus can be taken by multiple users.

In the case of BisqEasy, since the objective is to "get your first Bitcoin" it makes sense that once the user has gotten its first Bitcoin, they don't want to keep buying it using that offer.
With this target audience in mind, add a setting to close the offer (for the specific case of `Buyer as Maker`) once it's been taken.
The switch should be by default true (close once taken), but possible to change in settings.

**Comment by djing-chan** [comment]
By default offers get deleted now. Only if the user change the setting this changes.
