### ISSUE TITLE
Use different style for step icons at trade wizard

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1350]
The style used for the active current state and the past states is the same green.
It would be better to use a different style for past states.
<img width="330" alt="Screenshot 2023-11-10 at 08 12 36" src="https://github.com/bisq-network/bisq2/assets/116298498/6eea5f52-f780-40cf-b517-198a216349f1">

**Comment by HenrikJannsen** [comment]
@axpoems Can I assign you that?

**Comment by axpoems** [comment]
Yes, you can assign it to me.

**Comment by HenrikJannsen** [comment]
Changed in 2.1.0
