### ISSUE TITLE
Adjust min. reputation score in preferences

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1402]
It is currently set to 0 for dev testing and should be set to some reasonable value.

**Comment by darawhelan** [comment]
Tried doing some calculations using 1 BSQ = $1 :

**Account Age**
Max: 365 x 10 = 3,650

**Signed Account Age**
Max: 365 x 50 = 18,250

**Bonds (based on lock time of 70 days and have 3x value of 0.1 BTC bonded at day 1)**

Score: 1000 BSQ x (10,000/10,000)
Age score: 1000/100 
total score: 1000 x 100 = 100,000

**Burning (based on burning 1 x value of 0.1 BTC bonded ~ 300 BSQ)**
total score: 1000 x 100 = 300,000

I would therefore suggest, if the above is correct, then a reputation score of of 300,000 would be a conservative amount to set the minimum reputation score to in preferences. 

Locking 500 BSQ for 2 years would give someone a reputation score on day one of over 500,000 which seems reasonable for an experience Bisq seller.

Looking at the above I think the burnt BSQ should decay over a longer time period than 100 days. I would suggest 3,000 days (basically a very slow decay) to give it an advantage over bonding BSQ for 2 years.

The above it based on me having done the calculation correctly which I am not confident on. Just went of the screenshots.

**Comment by HenrikJannsen** [comment]
Actually I just saw that bonding has not max lock time, thus if someone locks a rather small amount for very long time they get a very high score. I will fix that by limiting the max locktime used for calculation to 700 days (100k blocks).

**Comment by darawhelan** [comment]
Well spotted. What are your thoughts on increasing the decay period for the burnt BSQ?

**Comment by HenrikJannsen** [comment]
> Well spotted. What are your thoughts on increasing the decay period for the burnt BSQ?

I am open to that. I hope you could find a way to run the app yourself and play around with the simulation tool, that might be very helpful to fine tune the numbers.

**Comment by darawhelan** [comment]
Based on the above two linked issues I think a min reputation score: 300,000 is appropriate.

The changes in: https://github.com/bisq-network/bisq2/issues/1453, and https://github.com/bisq-network/bisq2/issues/1454 change the reputation model from trying to avoid "a race to zero" to being something that can "accrue in value" over time.

Reputations should be hard to build and easy to lose. It makes sense for reputations to increase over time. A trader who has been on the platform for a long time with no issues should be considered more trustworthy than a new seller.

**Comment by djing-chan** [comment]
@darawhelan Do you think 100 000 is ok? With the other changes in the reputation calculations that would enable a seller who burns eaery months 75 BSQ to be selected by newbies. I fear that when we set the value too high that the burden for sellers is too high, as they earn only about 10-20% with low amount trades (e.g. 10 trades with 100 USD might give them a 100-200 USD profit).

**Comment by darawhelan** [comment]
@djing-chan I think the minimum reputation should be equivalent to the BSQ value of x1 max trade value which will start at 0.01 BTC. I would expect experienced sellers to achieve a reputation score far above 300,000.

**Comment by darawhelan** [comment]
Following discussion with @HenrikJannsen we both agreed that the reputation scores should be simplified.

It was suggested minimum reputation score should be **30,000**

## Account Age (AGREE)

Change max days to 2,000
Weight: 2.5
New max score = 5,000

---

## Signed Account Age Witness

Change max days to 2,000
Weight: 5
New max score = 10,000

---

## Burning BSQ

Weight: 100
No decay factor

300 BSQ burned gives a reputation score of 30,000 this score will persist with that users profile.

---

## Bonding BSQ

Weight: 10
Fixed limit: 50,000
3,000 BSQ bonded gives a reputation score of 30,000. After 50,000 blocks reputation stays until bond is unlocked.

**Comment by HenrikJannsen** [comment]
Replaced by https://github.com/bisq-network/bisq2/issues/1495
