### ISSUE TITLE
Missing error handling at trade protocol

### ISSUE THREAD

**Issue by djing-chan** [bisq-network/bisq2#1416]
If the take offer request fails at the maker side we only log an error but do not communicate it to the user nor to the peer.
This could lead that the seller is sending still their payment account data even the trade has failed at the first stage.
We should send back an error message to the taker in that case to indicate that the maker had gotten an error.
As well as show indication for the error to the user.

**Comment by djing-chan** [comment]
I can work on that

**Comment by axpoems** [comment]
I think if there is an error (apart from giving the user fb as mentioned), we should probably also change the state to `Cancel`/`Rejected` or maybe a new one `Invalid` which closes the trade directly.

**Comment by djing-chan** [comment]
> I think if there is an error (apart from giving the user fb as mentioned), we should probably also change the state to `Cancel`/`Rejected` or maybe a new one `Invalid` which closes the trade directly.

Yes, it is implemented as a new final state.
