### ISSUE TITLE
Horizontal bar should not appear if line can be displayed entirely

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1425]
Horizontal bar keeps appearing even if all the content can be displayed:
![image](https://github.com/bisq-network/bisq2/assets/145597137/fb5b7eee-f687-4717-b007-4737d4151a3c)

Moreover, it seems that *sometimes* the horizontal bar is overlapping the line itself. This should be fixed as well. Should look like in "My Open Trades".
![image](https://github.com/bisq-network/bisq2/assets/145597137/dbd6d703-447c-4241-b99f-2761820e54c0)
I am able to repro this behaviour when I get a chat for the first time.

**Comment by namloan** [comment]
Couldn't reproduce, is this still relevant?

**Comment by HenrikJannsen** [comment]
Probably fixed then.
