### ISSUE TITLE
tabView selection line looks buggy when notifications appear

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1426]
The `tabView` selection line should cover text + notification (if any).
Thus, make `tabView` selection line update every time notifications change.
![tabView](https://github.com/bisq-network/bisq2/assets/145597137/65c26ccf-8b42-458d-a4ce-204fb4da621e)

**Comment by HenrikJannsen** [comment]
Fixed with https://github.com/bisq-network/bisq2/pull/2484/commits/93f1b6b9257fd55c53fc2352e9feb555150f6634
