### ISSUE TITLE
Update the reputation calculation for 'Account Age' and 'Signed Account Age Witness'

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/bisq2#1453]
I think both  'Account Age' and 'Signed Account Age Witness' should accrue more reputation than they currently are able to:

## Current reputation calculations

**Account Age**

![Account Age](https://github.com/bisq-network/bisq2/assets/121062323/31a8941d-9b0c-476e-8259-ee4a7f60caed)

Current max reputation score: 3,650

**Signed Account Age Witness**

![Signed Account Age](https://github.com/bisq-network/bisq2/assets/121062323/e1b536eb-9ba4-4c59-b7b8-d9e78a604731)

Current max reputation score: 18,250

## Proposed reputation calculations

**Account Age**

Change max days to 2,000
Increase weight to 40
New max score = 80,000

**Signed Account Age Witness**

Change max days to 2,000
Keep weight at 50
New max score = 100,000

Reasoning: 

- Account Age and Signed Account Age Witness weight factor should be closer in score. 
- Users with aged accounts beyond 365 days should be given increased benefits. A user with an account age of 4 years should be given more benefits over a user with 1 year.
- Max score achievable for both should be increased.

Linked issue:

https://github.com/bisq-network/bisq2/issues/1402

**Comment by HenrikJannsen** [comment]
Account age is not a very secure data source, thus it did not get that much of weight. But I agree that its too low now.

**Comment by darawhelan** [comment]
Maybe a weight of '25' for the 'account age'.  Any less than half of the 'signed account age witness' seems to low to me.

**Comment by darawhelan** [comment]
Replaced with https://github.com/bisq-network/bisq2/issues/1495 will close this issue
