### ISSUE TITLE
Consider new Reputation Score 'Profile Age'

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/bisq2#1455]
The longer a user has had a profile the more invested they should be in not losing that profile.

Based on signed account age I think Bisq 2 profiles should accrue reputation at a rate of 50 reputation points per day.

Both buyers and sellers can accrue this reputation.

A seller might be keener to release the bitcoin post payment quicker to an aged buyer with a reputation of 10,000 (200 days old) than a new user with no reputation.

Linked issue:

https://github.com/bisq-network/bisq2/issues/1402

**Comment by HenrikJannsen** [comment]
Yes I was considering that as well, but dropped it as we show the profile age anyway and mixing it into reputation seemed redundant. The user can interpret the profile age for themself. So if there are 2 users with 0 reputation but one with very old profile and other with a new profile, that info can be used for trade decisions. 
Another aspect is that Bisq Easy is for newbies who by definition have a fresh profile age. We don't want to make it harder for them to trade to give too much weight on it.

But no strong opinion on it.

**Comment by darawhelan** [comment]
Retiring this idea for the moment. 

https://github.com/bisq-network/bisq2/issues/1495 has simplified reputation scores and we should see how this goes before making further changes.
