### ISSUE TITLE
What does setting a password do?

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/bisq2#1462]
When setting a password a little more info would be nice.

Does it encrypt the data?
Will I be asked for it at login?
If I lose the password will I be able to access my account? Should I protect it like a seed phrase?
 
![password](https://github.com/bisq-network/bisq2/assets/121062323/8d7d3e08-9dc0-4651-b84b-2ecda661dc14)

**Comment by HenrikJannsen** [comment]
Yes, agree.

Atm the pw protection does only encrypt the user data (one file of the db files). Once set the user need the pw to enter the app. If lost there is no recovery, the user profile is lost. so ppl should do a backup with the unencrypted data first.

Once the wallet is integrated it will encrypt the wallet, and it becomes more important. the wallets will come with a seed so losing the pw but having the seeds will not put your funds at risk, but open trades might fail if user profile is not accessible.

Could you suggest some text? We could add it like in Payment accounts. If needed also a "Read more" button with link to wiki.

Alternatively we could remove the pw screen for the launch as it is not very important in the current state and the scope for encrypting db files is maybe too narrow as well atm.

**Comment by darawhelan** [comment]
> Alternatively we could remove the pw screen for the launch as it is not very important in the current state and the scope for encrypting db files is maybe too narrow as well atm.

I agree with this. If there is is integrated bitcoin wallet then I think adding a password might be more troublesome than it is worth ATM.

**Comment by HenrikJannsen** [comment]
Ok, I will remove the tab
