### ISSUE TITLE
Validation of Bitcoin address

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#1473]
When filling in a Bitcoin address it should be validated to reduce unnecessary mediation cases because of typos.

e.g.
https://github.com/bisq-network/bisq2/blob/225b4db2265616049f38dc07aa5704bfc89adf46/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/states/BuyerState2.java#L126

**Comment by rodvar** [comment]
@HenrikJannsen @djing-chan I'll love to look into this one. My approach would be

 1. creating an util component that can recognize if a string is a valid BTC address or not
 2. Using that on every place I can find in the UI where we ask for BTC address
 3.  Show a warning/pop up when a string is not a BTC address (using the right i18n) -> I'm sure there is some reusable component for this right? 
 
 LMK! Cheers!

**Comment by djing-chan** [comment]
We should use the validation of the MaterialFextField. But we should be tolerant to allow users to go with non BTC address/tx as they might use another currency or L2 (liquid, RSK). 
We should not import any new dependency for the check from any btc library as we are not decided yet which bitcoin lib we will use. I guess some regex should do it...

**Comment by rodvar** [comment]
@djing-chan yep, we are on the same page - - I'll get into this one after the ones I'm starting to work on now, thanks!

**Comment by rodvar** [comment]
Starting work on this one
