### ISSUE TITLE
Validation of transaction ID

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#1474]
When filling in a transaction ID it should be validated to reduce unnecessary mediation cases because of typos.

e.g.
https://github.com/bisq-network/bisq2/blob/225b4db2265616049f38dc07aa5704bfc89adf46/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/states/SellerState3.java#L122

**Comment by djing-chan** [comment]
We should permit non-BTC transactions for more flexibility (e.g. traders use LN or other currencies). But we should show a warning popup if we detect an invalid BTC transactions.

**Comment by rodvar** [comment]
@djing-chan same for this one, happy to take it using the approach I've commented on https://github.com/bisq-network/bisq2/issues/1473

**Comment by rodvar** [comment]
Starting work on this one
