### ISSUE TITLE
Improve icons for the different chat domains and channels

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1514]
Some highlights (quoting @HenrikJannsen from [his comment](https://github.com/bisq-network/bisq2/pull/1502#issuecomment-1856196472) in PR #1502):
- Update icons with bisq2 green.
- The meetup has the same icon as events. Maybe we can find a replacement there. Same for support/gen support.
- The icon used at off topic looks more like trade and the trade icon looks more like markets. Not sure if there is a good fit for off-topic of the current icons...
- The Bisq and BTC icons are a bit small. Also markets. For the BTC icon the typical tilted version with a circle might be also better.
- I am also not so sure if the support icon is clearly enough recognizable. Maybe some other icon which is more typical for support would be better.
- If we use a header, we could also consider to use colored icons in larger size, similar as the markets in offerbook. I guess the design could benefit from a few light color drops (as in trade protocols).

**Comment by axpoems** [comment]
You can assign this to me.

**Comment by djing-chan** [comment]
I think that can be closed
