### ISSUE TITLE
Show reputation badge

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#152]
For now we likely use only the reputation based on the burned BSQ as that is verifyable and not violating privacy (like other reputation concepts would). To make it easy for new users to detect those trusted sellers, they should get a clearly recognizable badge next to the user icon/username which displays on rollover more information (e.g. sum of burned BSQ, duration of activity as seller,...).

Current concept is that trusted sellers need to burn min. 50 BSQ/DAO cycle. With each burning they increase their repuations. E.g. a seller who has burned 50 BSQ for 6 cycles get 300 BSQ and 6 cycles as duration displayed. Sellers could burn also more BSQ but a seller who burned 300 BSQ in 1 cycle might be less trustworthy than a seller who has been active since 6 months. Even if we do not verify if the seller has actually traded, just to do the burning over such a period can be considered as some "proof of work"   
and the likelyhood that a scammer prepares such long time for a scam is very low, opposed to a short term investment to try to scam newbies. But also then the scam risk is rather low IMO as scammers don't like to invest money upfront and the small trade amounts will likely not attract them in the first place. Also to get BSQ and learn about the process is already some "proof of work" as well.

All the other suggestions with feedback, rating, .... come with the problem how we can verify those in a decentralzied way. It is a hard problem and I am not aware of any solid solution for those without revealing privacy. So I think its better to stick with burned BSQ and only if we find out that this is not sufficiently safe or if one come up with a privacy protection solution for decentralized reputation we can extend it.

**Comment by alkum** [comment]
I agree, proof of burn is a good way to approximate trustworthiness in a decentralized and privacy-preserving setup.

> Current concept is that trusted sellers need to burn min. 50 BSQ/DAO cycle.

Adding terminology like "trusted seller" encourages laziness on the side of buyers. Trusted to what extent? Someone who burned 50 BSQ could be trustworthy for small trades. But if I want to scam someone of 1000 BSQ, then burning 50 to "gain their trust" is a worthwhile investment.

I guess one proposed alternative is to indicate the trustworthiness of a seller relative to the size of the current trade. In this case, total burned amount matters more than regularly burning.

Then again, it makes no sense to "require" someone to burn 1000 BSQ to be seen as trustworthy for trades of 1000 BSQ or less.

Another proposed alternative is to use relative trustworthiness. For example, "This seller has the 3rd highest reputation of current active sellers". If given a choice, a buyer would likely prefer a seller with a higher relative trustworthiness.

This is just food for thought. Overall I think your approach (50 BSQ/cycle to be "trusted seller") is the simplest and more than "good enough" for a start.

**Comment by chimp1984** [comment]
> Another proposed alternative is to use relative trustworthiness. For example, "This seller has the 3rd highest reputation of current active sellers".

Thats a good idea! 

> Burning 50BSQ should not make your reputation increase if you can trade more than 50BSQ at once.

Yes, one should not confuse that system with real security. But in our keybase OTC chats there is zero security and an even weaker "reputation" system and as far I am aware there have been no issues at all. I think all need to be seen in the right context. Small trade amounts, verbal communication, options for peers to make their own risk estimations by reading up chat history,....

>  think that using pure reputation systems, even if simply pointing to third parties à la Keybase
Keybase does not have a reputation system. Just linking your account to an external Twitter account does not add security either. It comes with high effort for user to make risk estimation based on all that content and loss of privacy and introduces unwanted dependencies.
We have to be aware that there are no decentralized privacy protecting reputation systems. If anyone thinks different please point me to one. WoT might be the best available but is also no success story.

> Maybe it's just that I don't understand full protocol.I guess that, at least, traders with that badge will have the honour to send the last their BTC to traders willing to get their first BTC. If that's all the scope of this prtocol, it seems ok.

The purpose is to bring the use case of the OTC keybase chat into Bisq with a bit better "security" + the new aspects of enhancing Bisq with more social aspects. Bring the experience of Satoshi squares or BTC meetups into Bisq. It is not only to let newbies buy small amounts of BTC but also to get some help for onboarding into BTC and Bisq and potentially find some people with whom one shares interests. In contrast to the cold "shopping/banking" experience from normal exchanges. 

It is NOT the goal to replace existing Bisq protocol or motivate hardcore Bitcoiners to use that. It is intended **for users we do not have atm** as they cannot use Bisq without BTC and/or its too complicate and overwhelming to them (not only Bisq UX but also BTC itself).

**Comment by MwithM** [comment]
> Keybase does not have a reputation system. Just linking your account to an external Twitter account does not add security either. It comes with high effort for user to make risk estimation based on all that content and loss of privacy and introduces unwanted dependencies.
We have to be aware that there are no decentralized privacy protecting reputation systems. If anyone thinks different please point me to one. WoT might be the best available but is also no success story.

Criptographically linking an onion address to a social network, github, ebay or hodlhodl kills privacy but I wonder if there's a market for something like this.
Probably first having what is suggested in the social trading protocol and others though.

**Comment by alkum** [comment]
> Maybe it's just that I don't understand full protocol.

@MwithM no need to.

Here's a short and snappy explanation of how Proof of Burn can be used to tell someone's reputation / trustworthiness: https://programmingblockchain.gitbook.io/programmingblockchain/other_types_of_asset/proof_of_burn_and_reputation

**Comment by MwithM** [comment]
> Imagine you burned 50 BTC for your reputation. And a customer want to buy 2 BTC of goods from you. 

I'll consider they're talking about BSQ :P

The problem comes when the trader who burns 50 BSQ can trade 2000 BSQ anonymously and being able to quickly create new accounts.

**Comment by chimp1984** [comment]
> I'll consider they're talking about BSQ :P

Ah yes ;-) Burning 50 BTC would be very solid reputation

> The problem comes when the trader who burns 50 BSQ can trade 2000 BSQ anonymously and being able to quickly create new accounts.

As said it must not be mistaken as (solid) security. It is better as what we have in keybase or what ppl have in OTC chats trades. Its intended for small amounts and if it would turn out that there is too much abuse we need to adjust. We should not over-think security here. Its not the goal. The goal is the social experience and convenience.

**Comment by alkum** [comment]
> As said it must not be mistaken as (solid) security. [..] We should not over-think security here. Its not the goal. The goal is the social experience and convenience.

Maybe the reputation badge could have a link "What is reputation?" pointing to a wiki page.

The wiki could describe in more detail what reputation is, what it means to burn BSQ, why would a seller do that, why such a seller is worthy of more trust than one without, etc.

**Comment by MwithM** [comment]
Another idea for the name: Star trader. Gold trader (bitcoin traders, using security deposits, are much better). For those, designing a badge is obvious.

**Comment by chimp1984** [comment]
Current state:

<img width="1101" alt="Screenshot 2022-04-25 at 10 43 16" src="https://user-images.githubusercontent.com/54558767/165062544-375a0d11-17ab-4fbe-bdff-15a129f5934c.png">
