### ISSUE TITLE
Add statistics for total network traffic

### ISSUE THREAD

**Issue by djing-chan** [bisq-network/bisq2#1543]
We show the send/received messages and bytes for every connection. We should also show the accumulated data in the nodes table. As connections get closed after 2 hours the data per connection is less valuable.

**Comment by rodvar** [comment]
Hi @djing-chan , I'd like to tackle this one this week as well any hints on where to start looking or any other comments you'd think useful?
Cheers!

**Comment by djing-chan** [comment]
In Connection there is a ConnectionMetrics. But we need to accumulate all to not lose the stats when connections get closed, which happens frequently. We want to see total network usage stats (num sent/received messages/bytes,...). There is a periodic logging of network stats, thats a good point to look at how the data are collected

**Comment by HenrikJannsen** [comment]
@rodvar I self-assigned me as I will work on related issues and it would increase merge conflicts if 2 devs work on that area.

**Comment by rodvar** [comment]
@HenrikJannsen happy to help with the code review on this one if you are keen let me know!

**Comment by HenrikJannsen** [comment]
Code review of any open PR is always welcome!
