### ISSUE TITLE
Improve notification handling on start up for messages in inbox

### ISSUE THREAD

**Issue by mrblue313** [bisq-network/bisq2#1546]
When starting up the application, the user gets a notification for every single message waiting to be delivered in the inbox, which in turn, needs to be dismissed/wait until dismiss automatically. If the are many messages (more than 4-5?), this does not give a good experience. We should find a better solution for this use case. We could apply some heuristics when delivering these notifications. One possibility could be to notify per channel, e.g. "new notifications in channel X".

**Comment by HenrikJannsen** [comment]
Yes true. We could send only 1 message at startup for all the pending notifications and after that behavior is as it is now. 
Wondering of OS notifications are needed at all at startup for pending messages, as the user is active on the app when starting it and OS notifications are mainly to notify a user who has the app in the background.
We could even add a feature to only send the OS notifications if the app is not focussed, or add a flag for that to the settings.

**Comment by HenrikJannsen** [comment]
Just to make clear, we do not deliver any notification at first startup. But still when a used has not been online for a while the notifications get stacked up quite a bit.

**Comment by HenrikJannsen** [comment]
On MacOs the notification center handles multiple notifications well. Nothing needed for that IMO.

For other OS where the native notification system does not handle it smart we could throttle the pipeline of notifications and create a generic notification for multiple notifications (E.g. You received xxx notifications from Bisq 2).

**Comment by axpoems** [comment]
I can look into this.

**Comment by HenrikJannsen** [comment]
This issue need to be fixed with priority as on Windows (11) the OS notification system does not handle that well and its very annoying to get 100s of notifications... 
I think to just not send out any notification at startup is the easiest and best solution.
