### ISSUE TITLE
Do not send notification for edited messages

### ISSUE THREAD

**Issue by mrblue313** [bisq-network/bisq2#1547]
When a message is edited, users get notified about that message again.

**Comment by HenrikJannsen** [comment]
I think it is a useful feature to get a notification that something changes. Technically we remove and add a message, so from that point it is correct. 
I checked it in Elements/Matrix and they don't show a notification.

As it would be technically a bit complicate to implement I think the cost/benefit ration is in favor of leaving it as it is.
I will close but if you feel its important to you and you are motivated to implement it, feel free to re-open.
