### ISSUE TITLE
Produce Bisq 2 intro video for webpage

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1570]
We should add a short (3-5 min) video to the Bisq 2 webpage which gives a quick overview about reasons, motivations, features and roadmap for Bisq 2.

**Comment by Ven32123** [comment]
@HenrikJannsen If I can get a windows download link for Bisq2 or Bisq Easy, I can look into making a video guide, motivations and features.  Let me know if you want help on this task.

**Comment by HenrikJannsen** [comment]
A contributor is already working on the video.
