### ISSUE TITLE
Improve video animation

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1571]
The Bisq Easy video starts with a screenshot of Bisq 2 which looks a bit weird in the popup as it looks just like being in the app.
It would be good to have a start image which makes it more obvious its a video.
Also the slides could be improved by animations and maybe displaying a mouse pointer.
The popup how the video is embedded might also use a different blur/darken effect to make it more clear its a video popup.

@axpoems Would you have some ideas how to improve that?

**Comment by axpoems** [comment]
I'll take a look into this.

**Comment by djing-chan** [comment]
Added milestone 2.0.0 but it is considered a "nice to have"

**Comment by HenrikJannsen** [comment]
Covered by https://github.com/bisq-network/bisq2/issues/1656
