### ISSUE TITLE
Add constraints to input text

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1585]
> We should also limit the length of the message. There is a limit in the p2p message anyway.

and if still needed, set a max height to `BisqTextArea`.

![image](https://github.com/bisq-network/bisq2/assets/145597137/95ac95d3-58af-49b4-93cf-f695ad8a0a0d)

**Comment by kuba-04** [comment]
hi @axpoems, where is that view, I don't see the problem when I run main branch locally.
![image](https://github.com/bisq-network/bisq2/assets/30311112/359dfc37-fea1-48fe-8669-3988e6883cfd)

**Comment by HenrikJannsen** [comment]
We should also limit the length of the message. There is a limit in the p2p message anyway.

**Comment by HenrikJannsen** [comment]
> hi @axpoems, where is that view, I don't see the problem when I run main branch locally.

Do you run latest main?

**Comment by axpoems** [comment]
> hi @axpoems, where is that view, I don't see the problem when I run main branch locally.

@kuba-04 - from your screenshot, it seems that you are not running latest. Also the bug is input text (not clear from your screenshot if you were looking at that).

> Do you run latest main?

@HenrikJannsen - Yes, this is latest main, just tested it now again.

**Comment by kuba-04** [comment]
@axpoems you are right, I was on an old version, still the new one doesn't have the horizontal scrolling issue on the input field. It adjusts the text and scrolls down vertically. 

@HenrikJannsen I could do that, what message length would you recommend?

**Comment by djing-chan** [comment]
We have already the limit from ChatMessage.MAX_TEXT_LENGTH (10 000) in place.
