### ISSUE TITLE
Improve FSM for parallel state transition paths

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1587]
We use a simple [FSM](https://github.com/bisq-network/bisq2/tree/main/common/src/main/java/bisq/common/fsm) implementation in Bisq2 but we are hitting already its limitations for the BisqEasy protocol. 

There are multiple parallel options how to transit to another state and currently we have implemented it with multiple paths. But I fear that is not a good way forward specially for more complex protocols in future. 

I am considering to add a feature similar like EasyBind.combine where one can combine multiple events and handle those to generate a new event. The FSM would then handle that result state. 

We want to keep the FSM as simple as possible to avoid risks due complexity and to make reasoning about the protocol easier. 

If anyone has more in depth experience with FSM or some suggestions please reach out. We should get that done before the launch to avoid potential update issues.

**Comment by HenrikJannsen** [comment]
@stejbac , @alvasw Do you have some inputs to that?

**Comment by djing-chan** [comment]
I can have a look into that
