### ISSUE TITLE
Use capability for upgrade to optimized inventory request solution

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1611]
As it is not expected that we can get a fast solution for optimized data requests (https://github.com/bisq-network/bisq2/issues/1602) we should ensure that once we switch to a better solution it does not require a network wide update.

As it is just a 2 party protocol I think it should not be a big problem. The future solution could be modeled as capability and the requester only use the new solution if the peer supports that capability.

We should ensure in the release that all that support for future update is in place.

**Comment by djing-chan** [comment]
I can work on that
