### ISSUE TITLE
Review TODOs

### ISSUE THREAD

**Issue by namloan** [bisq-network/bisq2#1624]
There are quite a few [TODOs in the code](https://github.com/search?q=repo%3Abisq-network%2Fbisq2+%2FTODO%2F&type=code&p=2). We need to double check whether any of those TODOs need to be resolved for the release - if so, create an issue for them in the  [2.0.0 milestone](https://github.com/bisq-network/bisq2/milestone/1).

**Comment by HenrikJannsen** [comment]
https://github.com/bisq-network/bisq2/issues/1634 was created to take care of the TODOs critical for the release
