### ISSUE TITLE
Offerbook Revision with additional Improvements

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1718]
Following up on #1572, these were the options considered to place the create offer button in the offerbook:

![ALL-create-offer-button](https://github.com/bisq-network/bisq2/assets/145597137/07da75de-0240-4c79-b9cb-28e14fb5dfba)

After some user testing and gathered feedback, I proceeded with option B.

Further improvements were done for this version, according to the feedback received from the current version that we have in the app.
The changes  are:

* Moved the 'Create Offer' button to the main window header to enhance its visibility and make it more related to the specific selected market.

* Relocated the crypto-fiat pair logo and market title to the main window header, this makes the whole offer book layout more coherent.

* Added the market's crypto-fiat rate to the header for easier reference.

* Renamed the column for fiat markets to 'Markets' for clarity.

* Moved the search function to the sub-header, making it consistent with the Markets column.

* Applied a dimming effect to the fiat logos when they are not selected, reducing the vibrancy of the logo colors.

In chat messages:

* Changed the color of the bubbles: the peer message bubble to a darker grey and my message bubble to a dark desaturated green. This colour differentiation improves user experience, even when message bubbles are positioned on opposite sides.

* Relocated the 'Reputation stars' to be nearer and alongside the user avatar for better association.

* Reduced the 'Take Offer' button's size and moved it closer to the offer text details.

* Decreased the font size and overall size of the message bubble for a more compact and readable chat interface.

<br>

Here is the proposed revision:
![offerbook-revision](https://github.com/bisq-network/bisq2/assets/145597137/e0570466-4169-4604-947d-3d747b755c20)

<br>
@HenrikJannsen what do you think?

**Comment by HenrikJannsen** [comment]
Looks good! Many good ideas implemented!

I am not so sure with the dark green color tone. I would prefer to stick with a grey tone. But not a too strong opinion about that.

Maybe we can drop the hamburger menu right to the create offer button. Opening the channel info could be done by clicking the market icon/headline. The trade guide could be added to the toolbox below or to the tab (right aligned as icon - not sure if that is good...).

**Comment by axpoems** [comment]
@HenrikJannsen  Thanks!

> I am not so sure with the dark green color tone. I would prefer to stick with a grey tone. But not a too strong opinion about that.

I agree and  understand your hesitation. This solution came after extensive testing and experimentation with various combinations of greys, outlines, and shades of green. Despite not finding a result that fully satisfied me, I decided to propose this option because it offered a highly functional outcome. Personally, I don't have strong feelings about this particular shade of green, it's derived from the Bisq 2 green `#56ae48`, and I aimed to maintain consistency with our color scheme. I've noticed that apps like Teams employ a similar strategy, using a darker, desaturated shade of their main app color for the message bubbles. My suggestion is to experiment with this color and become familiar with it. If it doesn't feel right, we can always revert to another option.

> Maybe we can drop the hamburger menu right to the create offer button. Opening the channel info could be done by clicking the market icon/headline. The trade guide could be added to the toolbox below or to the tab (right aligned as icon - not sure if that is good...).

Do you think it's not okay in its current place due to the possibility of accidental presses?
I believe there are several straightforward options that could work, such as placing it in the toolbox as you mentioned. Let me explore some alternatives then.

**Comment by HenrikJannsen** [comment]
> Do you think it's not okay in its current place due to the possibility of accidental presses?

No, just graphically it would feel better when the create offer button is right aligned without the hamburger box and would give it more weight as sole UI element there. But not too strong opinion either....
