### ISSUE TITLE
Offer not auto-renewing

### ISSUE THREAD

**Issue by djing-chan** [bisq-network/bisq2#1721]
Currently we use 10 days for TTL for offers. After the TTL expires the offer gets removed and the user would need to re-create the offer.
We could consider to re-publish the offer or use the refresh feature. 
Though it might be also a good effect to clear the offerbook from "bad" offers not taken.

@axpoems  @alvasw @pazza3
Any opinion about that?

**Comment by axpoems** [comment]
I think it would feel more natural for the offer to have a TTL of 14 days.
Also, I think we should go for re-publish (and not refresh).

Given this, and thinking in UX terms, I imagine that it would be useful to have the remaining days offers owned by the user have. We can add there a link to republish when it's about to expire.
Alongside with this, a popup alerting on offers about to expire/have expired can be added as well when opening the offerbook. This can also be used to explain this use case and ofc can be dismissed as to not appear again.

What do you think?

**Comment by djing-chan** [comment]
Increasing the TTL to 14 days (+40%) might carry the risk that the offerbook gets too many inactive offers. Newbies who take such offers but never get a response due an inactive maker would get frustrated. I would even suggest that we reduce it to maybe 2-4 days and use a refresh. So that makers who have not been online for longer than the TTL get removed their offers. The republish could happen then at new app start (using a popup asking the user or add a settings flag). 
We have to take care as in contrast to Bisq1 there are no costs included when creating an offer. Changing the TTL does not impact the data hash so we can change that later as well.

**Comment by HenrikJannsen** [comment]
I think https://github.com/bisq-network/bisq2/issues/2625 is a better approach.
