### ISSUE TITLE
Incorrect notification after trade got closed

### ISSUE THREAD

**Issue by djing-chan** [bisq-network/bisq2#1745]
After closing a completed trade on both traders I got that notification on one user.
![Screenshot from 2024-03-06 22-06-07](https://github.com/bisq-network/bisq2/assets/146422224/9ed60ab8-8ed6-44b7-bb49-caa256f3d21b)

**Comment by HenrikJannsen** [comment]
Seems https://github.com/bisq-network/bisq2/pull/1826 has fixed that bug as well. Could not reproduce it anymore. If still reproducable please re-open.
