### ISSUE TITLE
Clear notifications does not clear all notifications

### ISSUE THREAD

**Issue by djing-chan** [bisq-network/bisq2#1749]
Sometimes we get incorrect notifications. Clicking the clear all notifications button in the preferences does not clean up all pending notifications.

**Comment by HenrikJannsen** [comment]
It clears all notification in the left nav, but not inside of tabs when running on https://github.com/bisq-network/bisq2/pull/1826

**Comment by HenrikJannsen** [comment]
Actually after a new dev setup I cannot reproduce the bugs anymore with the recent fix.
