### ISSUE TITLE
Set Bisq Version Globally and Pass to Submodules

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#1768]
We set the Bisq version in many places:  
- in config files: `desktop.conf`,  `oracle_node.conf`, `rest-api.conf`, and `seed_node.conf`  
- in the packaging plugin: https://github.com/bisq-network/bisq2/blob/5ce28113b5710cad4c01bfd36bbfefe7ef0ea229/build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/PackagingPlugin.kt#L25  
- in the desktop module (for the fatJar):  https://github.com/bisq-network/bisq2/blob/ea32c88d0ec77042b18734b837b87a17af204fc7/apps/desktop/desktop-app/build.gradle.kts#L13
- in the DesktopAppLauncher: https://github.com/bisq-network/bisq2/blob/5ce28113b5710cad4c01bfd36bbfefe7ef0ea229/apps/desktop/desktop-app-launcher/src/main/java/bisq/desktop_app_launcher/DesktopAppLauncher.java#L64  

Release Managers must update the version number in all of these files. We could provide an bump version number script (like in Bisq 1) for now. I'd recommend to set the version globally and pass is to all sub-modules long-term.

Relates to #1764.

**Comment by HenrikJannsen** [comment]
Found it also in `gradle.properties`: `version=2.0.0`

**Comment by HenrikJannsen** [comment]
@alvasw Whats the easiest way for gradle scripts to read in the version number? Would a text file `version` with only the version string in it be good? Or better a property file?
For the config we could read in that file at startup and remove it from the config files.
We would though apply one global version to all applications (e.g. if no changes happened in oracle it still would get a new version number).

**Comment by rodvar** [comment]
@alvasw Happy to tackle this one. My approach would be to leave the application version definition ONLY on `gradle.properties`  and then using gradle task and a new static class link it to the java world and make it globally accessible updating all the current usages.

**Comment by rodvar** [comment]
started work on this one first

**Comment by rodvar** [comment]
@alvasw @HenrikJannsen hey guys! have a look at this when you have a moment! :)

 - https://github.com/bisq-network/bisq2/pull/2526
 
 I think we could get rid of version.txt (at least in common) and its usages but we can always do it in a cleanup PR, let me know your thoughts, cheers!

**Comment by rodvar** [comment]
I believe this one can be closed now :)
