### ISSUE TITLE
Fix stuck notifications in My Open Trades

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1784]
![image](https://github.com/bisq-network/bisq2/assets/145597137/32581da4-d6d8-4b8d-87bc-1067b59c64e0)

This happens when a user sends a message in the using the private chat inside My Open Trades. The notification is not marked as consumed and can't be dismissed.

**Comment by HenrikJannsen** [comment]
Related to https://github.com/bisq-network/bisq2/issues/1745 and https://github.com/bisq-network/bisq2/issues/1749

**Comment by HenrikJannsen** [comment]
Probably same issue as https://github.com/bisq-network/bisq2/issues/1749#issuecomment-2002333908

**Comment by HenrikJannsen** [comment]
Actually after a new dev setup I cannot reproduce the bugs anymore with the recent fix.
