### ISSUE TITLE
Add check if amount from blockexplorer lookup matches the trade amount

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1790]
If not matching show a warning.

**Comment by rodvar** [comment]
@HenrikJannsen Happy to look into this one. any hints on where to start looking in the code much appreciated!

**Comment by HenrikJannsen** [comment]
`bisq.desktop.main.content.bisq_easy.open_trades.trade_state.states.BuyerStateOnchain3b` and related classes

**Comment by HenrikJannsen** [comment]
Is already implemented
