### ISSUE TITLE
JavaFx has a 5 sec. delay at startup at Apple M3 macbook 

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1804]
There is a 5 sec delay due a timeout when starting a javafx app on a M3 macbook.

From the logs:
```
com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation
```

This also happens with the binary.

**Comment by namloan** [comment]
I've seen this log once on M2 Pro, but can't reproduce anymore. Does it always happen?

**Comment by HenrikJannsen** [comment]
For me on M3 it always happen. But might depend on the JDK used as well as if Rosetta is setup and used. Which JDK do you use? I use Azul.

**Comment by HenrikJannsen** [comment]
Does not work...
```
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4450d156'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib: dlopen(/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib, 0x0001): tried: '/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (no such file), '/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
java.lang.UnsatisfiedLinkError: /Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib: dlopen(/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib, 0x0001): tried: '/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (no such file), '/Users/dev/.openjfx/cache/17.0.1/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	```

**Comment by namloan** [comment]
I was using Amazon Corretto, but I've just tried with Azul and seems to also work OK. Maybe try upgrading the JavaFX version? JavaFX 21 was released in September and has some [performance improvements](https://github.com/bisq-network/bisq2/issues/948#issuecomment-1792317622). I noticed more lag in the app though when I tried it a few months back, but if it happens to fix the issue with M3 it may be worth to take another look to it.

**Comment by HenrikJannsen** [comment]
No success by using diff. jdks. 

Seems its that issue: https://bugs.openjdk.org/browse/JDK-8315657?focusedId=14612971&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14612971

Should be fixed in JavaFX 17 (https://github.com/openjdk/jfx17u/pull/164) and 21.

When inspecting the `com.sun.glass.ui.mac.MacApplication` it is not the latest version.

**Comment by HenrikJannsen** [comment]
Fixed with https://github.com/bisq-network/bisq2/pull/1810
