### ISSUE TITLE
User profile selection not working after profile was added in top left drowdown

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1807]

**Comment by namloan** [comment]
Is this the dropdown in User Options -> User Profile? can't see the issue

**Comment by axpoems** [comment]
I am able to repro. I think @HenrikJannsen is referring to the top right dropdown (i.e. the global user profile selection).
Steps:
1. Delete data dir and start up a new user.
2. Go to user options > Create new profile, and create yet another profile for that session.
Result: The global top right profile selection dropdown is static and does not show dropdown when clicking.

It works if you close the app and start again. And it also works fine with all the subsequent users that you create, but not with that first additional one that you create.

**Comment by namloan** [comment]
Thanks, could reproduce now. It only seems to happen in the very first start of the app when there's no data dir.

>  but not with that first additional one that you create.

Subsequent ones didn't work for me either

**Comment by HenrikJannsen** [comment]
I guess its just a incorrect initialization for a observer....
