### ISSUE TITLE
Space in Application Name

### ISSUE THREAD

**Issue by apemithrandir** [bisq-network/bisq2#1808]
Is there really a space in the application name on Linux? `/opt/bisq2/bin/Bisq 2`
Surely this must be an error.

**Comment by HenrikJannsen** [comment]
No thats not an error. You need to add   `\` if used in the terminal. E.g. `Bisq\ 2`.

But I agree that the space just adds more troubles and would also prefer to remove it. @alvasw what do you think?

**Comment by HenrikJannsen** [comment]
Remove in 2.0.2
