### ISSUE TITLE
Cannot watch Bisq Easy video on Ubuntu 23.10 Wayland

### ISSUE THREAD

**Issue by s373nZ** [bisq-network/bisq2#1830]
I'm getting the following error when trying to watch the Bisq Easy video:

```ERROR [JavaFX Application Thread] b.d.m.c.b.o.v.BisqEasyVideoView: mp4 not supported javafx.scene.media.MediaException: com.sun.media.jfxmedia.MediaException: Could not create player!```

The overlay renders, but the video won't play and I'm unable to close the window. Maybe some video encoding dependency is missing?

**Comment by HenrikJannsen** [comment]
Can you try to open https://github.com/bisq-network/bisq2/blob/main/apps/desktop/desktop/src/main/resources/bisq-easy-intro.mp4 to see if you can play that in the browser?

**Comment by s373nZ** [comment]
Yes, it plays in Brave Browser.

**Comment by HenrikJannsen** [comment]
We open weblink if an error is thrown by not supported codecs: https://github.com/bisq-network/bisq2/pull/1884
