### ISSUE TITLE
Improve style of matching offers in trade wizard

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1833]
When not selected the background is same as row bg.
Selection style also does not look great.
 
<img width="1334" alt="Screenshot 2024-03-17 at 17 43 24" src="https://github.com/bisq-network/bisq2/assets/116298498/6268157e-3eb2-4bab-99a0-a1ada0b89dd7">
<img width="1334" alt="Screenshot 2024-03-17 at 17 43 15" src="https://github.com/bisq-network/bisq2/assets/116298498/3ff777dd-e500-4603-8b39-5fc8d0126791">

@axpoems Could you have a look into that?

**Comment by axpoems** [comment]
Yes, I will work on this.
