### ISSUE TITLE
Bug with showing back button in take offer screen

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1853]
<img width="975" alt="Screenshot 2024-03-18 at 12 13 30" src="https://github.com/bisq-network/bisq2/assets/116298498/bfa4ab55-10f9-4f94-ae33-8459de812e7e">

**Comment by ItoroD** [comment]
@HenrikJannsen why is this a bug?

**Comment by HenrikJannsen** [comment]
Because there is no previous screen here. We only show other screens if the user has options to select.

**Comment by axpoems** [comment]
I have seen this here as well:

![image](https://github.com/bisq-network/bisq2/assets/145597137/138d3b0d-f46f-43dc-a8f2-bf8b7851dc93)

(Not able to repro yet though)

**Comment by HenrikJannsen** [comment]
Cannot reproduce anymore
