### ISSUE TITLE
UI freezes for about 15 seconds when displaying popups

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq2#1857]
# Summary
Clicking on an action button that causes a popup to be displayed (e.g. load website, take offer, delete profile, etc), the UI freezes for about 15 seconds before the popup is displayed; and also freezes when dismissing the popup.

I encounter this issue regardless if I run from the binary or from source.

# Environment
Ubuntu 23.10
Gnome 45.2
Wayland
JDK 17 (Corretto)

# Additional Details
It seems that something is blocking the JavaFx thread while trying to show the popup. I traced the cause to `timeline.play()` used in **bisq.desktop.common.Transitions.blur()**. If I comment that out, then I do not encounter the freezing when the popup is displayed. Though I am not sure of the underlying issue since so far I am the only one that has encountered (or at least reported) this issue.

A potential solution that worked for me was wrapping calls to methods that use `timeline.play()` in `UIScheduler.run()`. Though I am not experienced enough with JavaFx to claim that as a proper solution.

Note, there are various uses of `timeline.play()` in a few other classes, in addition to Transitions, that should be reviewed as well.

**Comment by devinbileck** [comment]
Turns out it is a result of failing to use hardware acceleration.

When I run the app with `-Dprism.verbose=true`, it shows the following:
```
Failed Graphics Hardware Qualifier check.
System GPU doesn't meet the es2 pipe requirement
GraphicsPipeline.createPipeline: error initializing pipeline com.sun.prism.es2.ES2Pipeline
*** Fallback to Prism SW pipeline
 vsync: true vpipe: false
```

If I force hardware acceleration with `-Dprism.forceGPU=true`, I no longer encounter the UI freezing.

**Comment by devinbileck** [comment]
For reference, graphics cards not listed [here](https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/com/sun/prism/es2/X11GLFactory.java#L31) will not enable es2 by default.

**Comment by HenrikJannsen** [comment]
Do you think setting `-Dprism.forceGPU=true` by default for all systems makes sense?

**Comment by devinbileck** [comment]
> Do you think setting `-Dprism.forceGPU=true` by default for all systems makes sense?

I am not sure why certain graphics cards are excluded from enabling hardware acceleration by default. It seems to work fine for me using that forceGPU setting, but perhaps may cause issues with certain systems. If this is a widespread issue, then perhaps we can use that setting by default. Or if it can be detected, then perhaps show a prompt (not popup) on startup to either instruct the user to enable it or automatically enable it for them.
