### ISSUE TITLE
Language mismatch in EasyBisq section [UI]

### ISSUE THREAD

**Issue by super-e** [bisq-network/bisq2#1858]
Hi,
I've freshly installed Bisq 2.0.1, it defaulted to Italian language (my system's setting). I noticed the Bisq Easy section was partially in Portuguese (like the "first steps" instructions for example). I switched the language settings to English, restarted the application, but with no effects.

The UI is a mix of Italian, English and Portuguese in the Bisq Easy section (see screenshot) while the rest of the UI is consistently in Italian (despite the English setting).

![Screenshot 2024-03-18 081958](https://github.com/bisq-network/bisq2/assets/25413725/98f25a97-4317-411a-b21f-c258fd19d5c1)

**Comment by HenrikJannsen** [comment]
English is used for all new translations strings which are not yet translated as the fallback language.
I just checked the translation strings and there is a mistake that the italien contains portuguese strings.
@hiciefte Could you check that?

**Comment by super-e** [comment]
> Seems to be chatGPT needs more oversight than I thought. I'll translate the Bisq Easy section again into Italian and will check if it is translated properly this time. Sorry about that!

No worries, in open-source spirit I scratched my own itch 😄

**Comment by hiciefte** [comment]
> > Seems to be chatGPT needs more oversight than I thought. I'll translate the Bisq Easy section again into Italian and will check if it is translated properly this time. Sorry about that!
> 
> No worries, in open-source spirit I scratched my own itch 😄

👍 I'll push your changes to Transifex as well, so all changes do not get overridden when the resource bundles are updated for the next release.

**Comment by HenrikJannsen** [comment]
@hiciefte Can we get those changes into next release?

**Comment by hiciefte** [comment]
Sure - I just wanted to wait if @super-e would be able to jump in for the remaining Italian translations as well. I translated all the other languages with chatGPT except  for Spanish (which @mwithm) will or has already taken care of. I'll pull everything and will complete the Italian translation if something is missing.

**Comment by HenrikJannsen** [comment]
Ok. As I assume the open translation work is anyway ongoing process, I will close that to tidy up the 2.0.3 issues....
