### ISSUE TITLE
Nothing happens when clicking URL link within a popup, until the popup is dismissed

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq2#1859]
# Summary
When clicking on a URL link within a popup, nothing happens until that popup is closed. At which time, a prompt will be shown confirming the URL to be loaded.

# Environment
Ubuntu 23.10
Gnome 45.2
Wayland
JDK 17 (Corretto)

# Steps to Reproduce
For example, when attempting to take an offer though the reputation is too low for taking the offer, an informational popup is shown containing a URL link. Clicking that link does nothing until the informational popup is dismissed.

# Additional Details
I suspect it to be a result of how the Popup manager queues popups for display, with only one popup able to be displayed at a time. So perhaps either clicking the URL link should dismiss the popup, or allow specific popups to be displayed overtop other popups.

**Comment by HenrikJannsen** [comment]
Fixed with https://github.com/bisq-network/bisq2/pull/1862
