### ISSUE TITLE
Dashboard - Active users info: single entities or user trade profiles count?

### ISSUE THREAD

**Issue by RequestPrivacy** [bisq-network/bisq2#1860]
Is the `Active users` info at the dashboard single entities or is this a count of all user profiles (where 1 user could have many, so 1:m relationship)?

In the latter case maybe a better wording for the info screen would be "Active (trade?) profiles". 

Also would be interesting to add a hint what "active" means.

**Comment by RequestPrivacy** [comment]
Thx for the explanation. 

> I agree that the wording is not clear, but being too technical/exact would be also difficult for users.

Not sure if "non-technical" people or non-power users actually care about these numbers whereas privacy conscious people could find it irritating that bisq knows how many "users" (i.e. entities) there are. In fact, that was why I asked. Since this isn't the case maybe it would still make sense for a wording of "profiles".

**Comment by HenrikJannsen** [comment]
@axpoems Do you have a recommendation for a renaming on that?

**Comment by HenrikJannsen** [comment]
Fixed in https://github.com/bisq-network/bisq2/pull/1896
