### ISSUE TITLE
Bisq2 app not opening anymore on MacOS

### ISSUE THREAD

**Issue by KainerW** [bisq-network/bisq2#1861]
Yesterday all worked fine. I closed the app yesterday and tried to open it again this morning:

![bisq-2-bug-not-opening](https://github.com/bisq-network/bisq2/assets/5575298/cbdeef85-7740-4132-bd16-45ef3b08538a)

On an Apple M1 with Sonoma 14.2.1

**Comment by KainerW** [comment]
This is the error message before that screen captured above  

![bisq2-error-Screenshot at Mar 18 11-11-20](https://github.com/bisq-network/bisq2/assets/5575298/fabb6421-a645-4e55-aea1-395ea0eba497)

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory in the data directory? `/Users/USER/Library/Application\ Support/Bisq2 `

**Comment by KainerW** [comment]
That fixed it. 

BTW: Is it normal to have two exactly same named folders there? 
![bisq-2-folders-liobrary](https://github.com/bisq-network/bisq2/assets/5575298/25cf0409-acb6-4534-83ab-73c04e80b279)

**Comment by HenrikJannsen** [comment]
> BTW: Is it normal to have two exactly same named folders there? ![bisq-2-folders-liobrary](https://private-user-

Do you have v2.0.1? That issues was a known issue in v2.0.0

**Comment by KainerW** [comment]
I am on 2.0.0 yes.

Is there a way to update without losing my data in the app?

**Comment by HenrikJannsen** [comment]
Please install 2.0.1 from Github. User data are preserved.
