### ISSUE TITLE
Buyer never received seller's payment account data, but canceling is not possible 

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1863]
Received this from a user
![image](https://github.com/bisq-network/bisq2/assets/124399749/63fde127-0ae9-439e-97dc-c61a773fffe1)
when he tries to cancel, he sees this
![image](https://github.com/bisq-network/bisq2/assets/124399749/6009b347-d34a-449a-8c79-051a54b320e1)

but he reports never receiving the payment data for the trade

**Comment by axpoems** [comment]
@suddenwhipvapor is this screenshot really from a seller? 

This image should only be on the buyer side
![image](https://github.com/bisq-network/bisq2/assets/145597137/07c526ff-24d3-4d9e-a581-0cb4b9338862)
