### ISSUE TITLE
Backup directory setting does not persist

### ISSUE THREAD

**Issue by s373nZ** [bisq-network/bisq2#1864]
When setting the backup location to a directory under Settings > Utilities, I am able to perform a backup, but when I navigate away from that interface, and then back to it, the directory setting is blank again. It should remember the backup location.

**Comment by stevednm** [comment]
Same issue, using Bisq2 in Linux (Linux Mint 21.3 XFCE edition).

**Comment by s373nZ** [comment]
I'm also on Linux (Ubuntu 23.10).

**Comment by HenrikJannsen** [comment]
Will get added to upcoming release: https://github.com/bisq-network/bisq2/pull/2173
