### ISSUE TITLE
Offerbook not connecting peers who pair up to make a transaction. I posted an offer to Purchase, a Seller accepted. 

### ISSUE THREAD

**Issue by Ottiz** [bisq-network/bisq2#1865]
I have posted an offer in the Offerbook to make a purchase, I have a Seller who accepted and confirmed via private chat,
I do not have any open trades with the seller when I look at "My Open Trades"

**Comment by HenrikJannsen** [comment]
There have been issues with network connectivity. It should be resolved in 2.0.2.
