### ISSUE TITLE
Error "The peer's trade failed win an error caused by: IllegalArgumentException, FsmException"

### ISSUE THREAD

**Issue by jdmconnected** [bisq-network/bisq2#1871]
Error thrown after initiating trade:
The peer's trade failed win an error caused by: IllegalArgumentException, FsmException

![Screenshot 2024-03-19 105903](https://github.com/bisq-network/bisq2/assets/30991606/5c7f2b8f-d602-4ecf-839d-b689af8206ef)
[bisq.log](https://github.com/bisq-network/bisq2/files/14652394/bisq.log)

**Comment by HenrikJannsen** [comment]
Happened at `BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:112)`
which checks:
```
  checkArgument(mediator.equals(takersContract.getMediator()), "Mediators do not match. " +
                        "mediator={}, takersContract.getMediator()={}",
                mediator, takersContract.getMediator());
```

It might have happened in the time when we banned temporarily one mediator to avoid a bug at the mediator selection. One user might have received the ban message and the other not.

We should provide more user-friendly error messages here, but there are many checks and its not clear yet how to do that in an efficient way...
