### ISSUE TITLE
New chat event notification tag sometimes stuck, and make offerbook notifications more granular

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1876]
Two more things that are minor issues and yet would improve the ux, especially for the team itself:
- I sometimes see that the new messages badge is stuck and even clicking on the relevant section, and scrolling each currency offerbook chat, it will stay there: 
![image](https://github.com/bisq-network/bisq2/assets/124399749/52a2c56c-3fb1-432c-ba65-0e982e02e2b0)
this thing happened now in the offerbook section, and I think it did at least once more in the past in the same manner, but I can't say 100% that it didn't happen with other rooms as well
- when the new event is in the offerbook section, you can't tell which one(s) of the rooms has new messages, and that's also quite important to be able to follow through easily, so adding a new event badge near each offerbook room would benefit this, maybe even allowing under settings to first order for "chats with new events", and then for "number of offers"

**Comment by hiciefte** [comment]
I can try to have a look at this issue.

**Comment by HenrikJannsen** [comment]
Should be resolved with latest bugfixes.

The feature request with badges for markets should be added as new issue and require discussion as @hiciefte pointed out.
