### ISSUE TITLE
Invalid input on trade price

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1886]
A user reported this:
https://recordit.co/EqTtIVHzv1

**Comment by MwithM** [comment]
I still had this issue with 2.0.2, was solved by changing system language to English.

**Comment by HenrikJannsen** [comment]
Yes offers created with other language and not running the version where it got fixes will still cause the issue. Not sure if the fix was in 2.0.2 already, I guess not.
