### ISSUE TITLE
Only republish user profile if used

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1904]
At the moment we republish all the profiles a user has every time a user gets online. We should only republish a profile if that actual profile was used.

Ref: https://github.com/bisq-network/bisq2/blob/main/user/src/main/java/bisq/user/identity/UserIdentityService.java#L290

**Comment by HenrikJannsen** [comment]
By https://github.com/bisq-network/bisq2/pull/2367 this will be the case (republish is only triggered by user activity on selected profile).
