### ISSUE TITLE
Fix notification issues

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1905]
Remaining issues in the notification system that needs fixing:

- Sometimes 'Leave chat' message is not sent.
- Sometimes reset button is not resetting everything (this applies only to the tab badge)
- Sometimes seeing this: every time I receive a new PM, I get notified for all of the ones I haven't yet read + that one
- Corner cases that need special handling:
    - What do to once a user leaves a trade chat?
    - What do to once a user leaves private chat?

**Comment by axpoems** [comment]
I can look into this and propose UX solution for the unhandled scenarios.

**Comment by HenrikJannsen** [comment]
See also https://github.com/bisq-network/bisq2/issues/1361 and https://github.com/bisq-network/bisq2/issues/1546

**Comment by HenrikJannsen** [comment]
Should be resolved with latest bugfixes
