### ISSUE TITLE
automate sending ETH 

### ISSUE THREAD

**Issue by skaunov** [bisq-network/bisq2#1925]
for permission-less kind of deals (MultiSig) it would be beneficial if Bisq could just propagate/send-out corresponding tx when the offer for buying via ETH is taken
maker would be saved from typing routine and mistyping risks, taker would enjoy fastest possible time, mediators would be off-loaded from this portion of trades since it hard to imagine a mediation case here

**Comment by HenrikJannsen** [comment]
Do you refer to Bisq 1 or Bisq 2? Bisq Easy in Bisq 2 has no support for ETH...

**Comment by skaunov** [comment]
Oh, I thought Bisq-2 is overtaking Bisq-1 and all *new* features should be created here. I even remember a team member was saying to me that Bisq-1 will be sunset when MultiSig will be implemented. Could you, pls, update me on the changes since. :confused: 
> Do you refer to Bisq 1 or Bisq 2? Bisq Easy in Bisq 2 has no support for ETH...

**Comment by HenrikJannsen** [comment]
Yes once we have implemented Bisq multisig Bisq 2 will replace Bisq 1 to large extent. But that will still take a while. Until that Bisq 1 is still continuing as usual and Bisq 2 is a separate project.

**Comment by pazza83** [comment]
> for permission-less kind of deals (MultiSig) it would be beneficial if Bisq could just propagate/send-out corresponding tx when the offer for buying via ETH is taken

For Bisq 1 I created a similar issue here: https://github.com/bisq-network/bisq/issues/6664
