### ISSUE TITLE
Reputation of wrong chat peer's reputation score is shown

### ISSUE THREAD

**Issue by polishboi** [bisq-network/bisq2#1928]
Version: v2.0.1
Platform: MacOS

1. Bisq Easy -> Offerbook -> Sell offer of User A -> Private message User A
2. Bisq Easy -> Offerbook -> Sell offer of User B -> Private message User B
3. Bisq Easy -> Private Chats -> User A -> Correct reputation is shown in "Chat peer" to the right of "My profile", Correct reputation is shown in "Chat peers" in User list for user A
4. Bisq Easy -> Private Chats -> User B -> INCORRECT reputation is shown in "Chat peer" to the right of "My profile" It's actually the reputation of User A!, Correct reputation is shown in "Chat peers" in User list for user B
5. Switch back and forth between the users and the reputation stays incorrect, i.e. swapped for A and B
6. Go to another tab e.g. "Trade protocols" or restart the app and when you open "Bisq Easy -> Private chats" and don't click anything the default state will be correct until you change the user

**Comment by HenrikJannsen** [comment]
Can you still reproduce that in v 2.0.4? I cannot reproduce it.
