### ISSUE TITLE
Use payment methods logos instead of text in Bisq Easy offer message

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1929]
![image](https://github.com/bisq-network/bisq2/assets/145597137/699c2bb4-9f5f-45d5-82b6-8afe9cc6cc96)

For instance, in this case, instead of "Wise", we should show the Wise icon.
Alongside with this, we could add a filter for payment methods.

**Comment by ItoroD** [comment]
filter for payment method is really useful.
