### ISSUE TITLE
CPU at 100%

### ISSUE THREAD

**Issue by ruben2k1** [bisq-network/bisq2#1931]
After being open for 30 seconds, the program starts consuming 100% of the processor

**Comment by HenrikJannsen** [comment]
Can you provide logs? Which version 2.0.1?

**Comment by ruben2k1** [comment]
Yes, I assume that 2.0.1 is the latest version published on bisq.network/downloads for download on Windows

**Comment by HenrikJannsen** [comment]
You see the version on the top left under the bisq logo.

**Comment by HenrikJannsen** [comment]
Do you still have those issues with version 2.0.4?

**Comment by ruben2k1** [comment]
No, it's solved
