### ISSUE TITLE
Add Bolivian Boliviano (BOB)

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1952]
A user in Bisq2 chat reported not being able to make an offer because BOB is missing.

**Comment by HenrikJannsen** [comment]
We only support currencies where we have a price feed. We would need to add that currency to the price feed. 
@jmacxx  Could you have a look if its feasible to add BOB to the price feed?

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/bisq2/discussions/2310 for the problem about adding niche markets

**Comment by rodvar** [comment]
Starting work on this

**Comment by HenrikJannsen** [comment]
Implemented with https://github.com/bisq-network/bisq-pricenode/pull/52
