### ISSUE TITLE
bisq2 stalls at 50% in splash window

### ISSUE THREAD

**Issue by richardalg** [bisq-network/bisq2#1984]
No issues reported in the build process on Debian Linux with AMD64 system 
executed   ./gradlew desktop:desktop-app:run
logfile should be attached 
Error reported "An error occurred at initialising Bisq: java.util.concurrent.Timeout exception"
[bisq.log](https://github.com/bisq-network/bisq2/files/14854764/bisq.log)

**Comment by fsignup** [comment]
I am having same problem. Stuck at 50 % with Java.util.concurrent.timeout exception. 
april 2024.  Fresh Arch linux install (although i am a noob). 
Installed bisq2 from AUR package. 

Bisq 1 runs just fine.

**Comment by HenrikJannsen** [comment]
Can you just restart? There are known issue with Tor startup, likely resolved in next release. If it does not start up after several attempts open the data directory and delete the tor folder.

**Comment by richardalg** [comment]
Thanks for the replies. 
I have had a machine shutdown and restart prior to restarting Bisq2. 
The splash screen again appeared to stall with the tor onion at 50%, however the startup process continued. 
Thus far, everything seems to work.
