### ISSUE TITLE
Use newly added StandardTable where appropriate

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1988]

**Comment by rodvar** [comment]
@HenrikJannsen do you think you could add a description to this one when you have a min? Thanks!

**Comment by HenrikJannsen** [comment]
At areas where we use the standard table (not specially tweaked ones like in offerbook) we should replace them with the new StandardTable (used in reputation). It comes with useful default features like search, export to csv, default data sorting, implicit SortedList and FilteredList,...

**Comment by HenrikJannsen** [comment]
Will work on that as it will make work on https://github.com/bisq-network/bisq2/issues/2576 easier....
