### ISSUE TITLE
Start trade wizard not working well

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#2002]
When I take an offer using the start trade wizard I see the following:
* Everything seems to have worked. However, on the app of the user who took the offer, the trade looks like this:

![image](https://github.com/bisq-network/bisq2/assets/145597137/5def6a85-174b-4fec-a786-f861c4bf5ee2)

* On the other side, the notification that the offer was taken is received but no trade can be found.

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0
