### ISSUE TITLE
Reputation ranking ordering search and ordinality

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2040]
I noticed #2014 but that's about something specific and I would be going offtopic in that issue.
Currently, the columns on the ranking section can be rearranged horizontally, and the reputation score column has a "descending" arrow in it, making it look like it can be reversed, but clicking on the column header does not actually reverse the order, so I think that arrow is there to make it clear the ordering is descending by default, not that it can be reversed.

I think the following upgrades would be beneficial:
 - add ascending/descending ordering capabilities to score, age, and profile name 
 - add search function for profile name (this could make "order by profile name" apparently unneeded, but consider the case where someone remembers the first few letters of a profile name but is not sure about the full spelling, for example "satcat" vs "sandcat", this last case would be better searchable by ordering the profile name column, instead of using a fulltext search)
 - add an ordinal column relative to the descending score ranking, so that 1st will be the highest scoring profile, and Nth will be the least scoring profile (for those who have the same score, the ordinal value will be the same, and starting from the next lower value the ordinal will be increased accordingly, for example if 10 people have the same score of 1000, and they are all 56th in the ordinal ranking, someone with a score of 999 will be 66th, and not 57th)

**Comment by HenrikJannsen** [comment]
Some of the above is impl. for 2.0.3.

**Comment by HenrikJannsen** [comment]
Can you look at 2.0.4 if anything is still missing? If so please open new issue with missing items.
