### ISSUE TITLE
Tagging multiple users makes the application freeze; mitigation suggestion

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2043]
I am running 2.0.2 from source (installing from deb yields a javafx error when starting), and I just tried tagging two users in a chat message: the first one took a while with a considerable delay in showing the possible results (I use bisq2 on a i7 8700k with 16gb of ram, running debian), while the second one stopped showing results and the application hung altogether.
The running logs showed
`WARN  [Scheduler-540-0] b.n.p.s.p.e.PeerExchangeService: We have a not completed future. We drop that call and return.`
around that time, plus others like
`WARN  [NetworkService.network-IO-pool-1456] b.n.p.n.Connection: Message not sent as connection has been shut down already. `

which I understand are not relevant to the issue itself, but rather the locking routine that prevented other processes from doing their job.

Since I noticed the potential results will start showing immediately after a single letter is typed near `@`, I thought it is maybe more resource efficient to start the search after at least 3 letters are typed?

**Comment by HenrikJannsen** [comment]
You mean with tagging to use the mention popup? Do you run latest main version? Always update before running as there are many merges...

**Comment by suddenwhipvapor** [comment]
Yes, what I am talking about is the mention popup, the one that comes up when you type `@` followed by the first characters of a profile name.
I cloned the 2.0.2 tag specifically and am running from that one

**Comment by suddenwhipvapor** [comment]
I cloned the whole repository without the branch option to specifically select 2.0.2 and restarted after rebuilding, this time I was able to tag 3 users one after the other and the bug didn't show itself...

**Comment by HenrikJannsen** [comment]
If you run from source its better to run lastest main, then you help testing as well. Many bugs in 2.0.2 are fixed already...

**Comment by suddenwhipvapor** [comment]
looks like this has no business staying open anymore 🙆🏻‍♂️
