### ISSUE TITLE
TradeWizard: Truncation of Strings

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#2057]
In the confirmation screen the content of one label is too long so it is truncated. But there is no tooltip set to show the full content of the label in German. There is also a grammar error in the translation which is caused by the way how the "Buy/Sell Bitcoin" label is constructed in code.

<img width="1468" alt="Bildschirmfoto 2024-04-15 um 11 36 07" src="https://github.com/bisq-network/bisq2/assets/150681275/46744d50-afff-4a85-92d8-03a7d2697d59">

**Comment by HenrikJannsen** [comment]
Can we try to tweak the translations?
