### ISSUE TITLE
Trades rejected still in "My open trades" section

### ISSUE THREAD

**Issue by eolinlovecraft** [bisq-network/bisq2#2068]
hi,
Bisq version: v2.0.2
Java: 
> ```
> openjdk version "17.0.10" 2024-01-16
> OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
> OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)
> ```

Before exchange of account detail I rejected a trade. I got the following message:
![image](https://github.com/bisq-network/bisq2/assets/55882356/9a82cb03-1af3-4c85-9b95-0e5ae929b323)

and I pressed Yes button.
Then in the chat peer windows appear <username> rejected the trade with a orange arrow icon (
![image](https://github.com/bisq-network/bisq2/assets/55882356/9fac1098-ed85-40e8-a66e-80f67a43f255)
finally, this orange icon is converted to red icon (Sending message failed) and the trade is kept in My optn trades forever.

how can we remove the rejected trades?

regards,

**Comment by HenrikJannsen** [comment]
We need to ensure the close button is still visible in case of a failed trade.

**Comment by HenrikJannsen** [comment]
Probably fixed by various bugfixes.
