### ISSUE TITLE
Java exception when computer lock

### ISSUE THREAD

**Issue by eolinlovecraft** [bisq-network/bisq2#2085]
Hi,
OS:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

Bisq version: 2.0.2

when the computer goes to lock while Bisq2 is open when I unlock I found the following error:

> Apr-16 10:09:56.692 [AWT-EventQueue-0] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
> 	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
> 	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(XTrayIconPeer.java:223)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Bisq2 continue working without problems.

regards,

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
