### ISSUE TITLE
Private chats do not get updated when focused

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2092]
I finally could get both my nodes to connect, so I started doing test trades.
Something I noticed, is that while 2.0.3 makes private messaging stable (on 2.0.2 I could never make private messages go through), even if the sending party sees "peer has downloaded mailbox message", it could happen the other one will not see anything in the incoming chat in the bottom panel, as long as the trade view is in focus. You either have to change to another tab and then back to trades to see the message, or detach the chat, and in that case the trade becomes visible.
I have noticed this behaviour several times, but now for example I am testing again and it's working as expected several times in a row, so it's not a constant issue.

**Comment by suddenwhipvapor** [comment]
Title updated: after further testing, all private chats act like this between two instances, both over 10 connections, either in trade, support or discussions sections, and this is verified in 2.0.4.
The first message, the one that opens the chat, is correctly displayed by the receiver, but all the following messages are not, unless the receiver moves away from the private chats display and comes back to it.

**Comment by HenrikJannsen** [comment]
I cannot reproduce that.

**Comment by HenrikJannsen** [comment]
I will close as long no one else reports it as not reproducable. If others report as well please request exact environment info.
