### ISSUE TITLE
Initialising applicationService failed

### ISSUE THREAD

**Issue by CleverSausages** [bisq-network/bisq2#2108]
There was a electricity failure  while using Bisq2.
When the electricity supply returned and I started my PC I was unable to use Bisq2 as it  was reporting an error.

Restarted PC ... same issue.
Uninstalled Bisq2. 
Downloaded Bisq2.
Same problem.
Also details of error weren't copied to clipboard on pressing any button.

I'm attaching the log file as requested.

[bisq.log](https://github.com/bisq-network/bisq2/files/15077134/bisq.log)

**Comment by HenrikJannsen** [comment]
Do you use latest release 2.0.3? You can delete the tor directory inside the data directory (<HOME_DIR>\AppData\Roaming\Bisq2\). Also restart your computer (sometimes ports stay block if a process crashes).

**Comment by CleverSausages** [comment]
Yes I'm on 2.0.3.
I deletedthe dir suggested, uninstalled, reinstalled and it's now working.
Thanks. 
#2108 possibly looks to be the same error.

**Comment by MwithM** [comment]
I found this after insalling 2.0.4
Tried the same things as the op.
