### ISSUE TITLE
Let user see details he provided himself, even before the trade peer needs to see them

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2129]
As per a user request.
Right now there is a set sequence to show details to the trade party that needs them: first buyer sees seller details, then when payment has been started, seller sees buyer's address.
A user complained he would like to see the address he provided himself, as soon as he sends it, even if it's not time yet to send the btc

**Comment by HenrikJannsen** [comment]
@axpoems I was also thinking that we should add the details in the log messages. By that users can look up what they have sent.

**Comment by HenrikJannsen** [comment]
It is added to the log message in 2.0.4
