### ISSUE TITLE
BISQ 2 - PopOS - Ubuntu-122.04.1 - Error loading

### ISSUE THREAD

**Issue by dodao5** [bisq-network/bisq2#2147]
........                  ......                                                                         
                ..............                ......                                                                         
              .................               ......                                                                         
            ......   ..........   ..          ......                                                                         
           ......      ......   ......        ...............        .....     .........         ..........                  
          .......              ........       ..................     .....   .............     ...............               
          ......               ........       ..........  .......    .....  ......   ...     ........   .......              
         ......                   .....       .......        .....   .....  .....            .....        ......             
         ......    ...        ...             ......         ......  .....   ...........    ......         ......            
         ......   .....      ....             ......         ......  .....    ............  .....          ......            
          ......                               .....         ......  .....         ........ ......         ......            
           ......       ....        ...        ......       ......   .....    ..     ......  ......      ........            
            ........     ..      .......        .................    .....  ..............    ...................            
             ..........       .........           .............      .....   ............       .................            
               ......................                 .....                      ....               ....   ......            
                  ................                                                                         ......            
                        ....                                                                               ......            
                                                                                                           ......            

 
May-05 22:11:04.499 [main] INFO  b.a.ApplicationService: Data directory: <HOME_DIR>/.local/share/Bisq2 
May-05 22:11:04.500 [main] INFO  b.a.ApplicationService: Version: 2.0.3 
May-05 22:11:04.515 [Scheduler-65-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 508 MB; Used memory: 11.23 MB; Free memory: 496.77 MB; Max memory: 7.805 GB; No. of threads: 2
************************************************************************************************************************ 
May-05 22:11:05.095 [main] INFO  b.p.PersistenceService: Read persisted data from:
<HOME_DIR>/.local/share/Bisq2/db/cache/banned_user_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/cache/bisq_easy_offerbook_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/cache/network_service_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/cache/public_discussion_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/cache/public_events_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/cache/public_support_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/account_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/bisq_easy_open_trade_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/bisq_easy_trade_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/identity_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/key_bundle_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/mediator_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/moderator_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/private_bisq_easy_private_chat_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/private_discussion_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/private_events_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/private_support_chat_channel_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/resend_message_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/private/user_identity_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/account_age_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/bisq_easy_offerbook_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/bisq_easy_open_trades_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/bisq_easy_private_chat_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/chat_notifications_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/discussion_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/events_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/market_price_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/message_delivery_status_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/profile_age_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/settings_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/signed_witness_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/support_channel_selection_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/tor_peer_group_store.protobuf
<HOME_DIR>/.local/share/Bisq2/db/settings/user_profile_store.protobuf 
May-05 22:11:06.043 [JavaFX Application Thread] INFO  b.d.DesktopExecutable: Java FX Application launched 
May-05 22:11:06.354 [PreventStandbyMode-0] INFO  b.d.c.s.Inhibitor: Started -- disabled power management via /usr/bin/gnome-session-inhibit --app-id Bisq --inhibit suspend --reason Avoid Standby --inhibit-only 
May-05 22:11:06.513 [JavaFX Application Thread] INFO  b.s.SecurityService: initialize 
May-05 22:11:06.522 [JavaFX Application Thread] INFO  b.d.DesktopApplicationService: New state INITIALIZE_NETWORK 
May-05 22:11:06.522 [JavaFX Application Thread] INFO  b.n.NetworkService: initialize 
May-05 22:11:06.553 [NetworkService.network-IO-pool-0] INFO  b.n.p.ServiceNode: New state INITIALIZING 
May-05 22:11:06.555 [NetworkService.network-IO-pool-0] INFO  b.n.p.n.t.TorTransportService: Initialize Tor 
May-05 22:11:06.566 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Error at networkFuture.initialize java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't create torrc file: /home/smiley/.local/share/Bisq2/tor/torrc
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't create torrc file: /home/smiley/.local/share/Bisq2/tor/torrc
	at bisq.network.tor.common.torrc.TorrcFileGenerator.generate(TorrcFileGenerator.java:59)
	at bisq.tor.TorService.createTorrcConfigFile(TorService.java:179)
	at bisq.tor.TorService.initialize(TorService.java:74)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

May-05 22:11:06.567 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't create torrc file: /home/smiley/.local/share/Bisq2/tor/torrc
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't create torrc file: /home/smiley/.local/share/Bisq2/tor/torrc
	at bisq.network.tor.common.torrc.TorrcFileGenerator.generate(TorrcFileGenerator.java:59)
	at bisq.tor.TorService.createTorrcConfigFile(TorService.java:179)
	at bisq.tor.TorService.initialize(TorService.java:74)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

May-05 22:11:06.568 [NetworkService.network-IO-pool-0] INFO  b.d.DesktopApplicationService: New state FAILED 
May-05 22:11:06.703 [JavaFX Application Thread] INFO  b.d.DesktopView: Attaching view to stage took 358 ms 
May-05 22:11:11.983 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = kde-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
May-05 22:11:11.986 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory 
May-05 22:11:11.987 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = gnome-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
May-05 22:11:11.989 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory 
May-05 22:11:11.990 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = xdg-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
May-05 22:11:11.993 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Process is running.

**Comment by dodao5** [comment]
@pop-os:~/bisq2$ java -version
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor folder in the data directory?

**Comment by dodao5** [comment]
So I done that and it did not even run the bisq anymore. So I just deleted it all and started again with 

git clone https://github.com/bisq-network/bisq2
cd bisq2

./gradlew build


./gradlew desktop:desktop-app:run

Which has worked. What I think it was after I installed JDK 17 and added the JAVA_HOME path variable and rebooted was still the issue. But uninstall everything and built it again with the JDK already in place seemed to like it more. Mabye add it JDK 17 as a pre req before downloading and building the package. Thank you for your help I got there in the end.

**Comment by HenrikJannsen** [comment]
In https://github.com/bisq-network/bisq2/blob/main/docs/dev/build.md its mentioned that Java 17 is needed. I will add it to the readme as well...

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
