### ISSUE TITLE
Add Egiptian Pount EGP

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2148]
As per user request

**Comment by HenrikJannsen** [comment]
We need to get it added to the price node. We only can support currencies which are delivered by the price node.

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/bisq2/discussions/2310 for the problem about adding niche markets

**Comment by rodvar** [comment]
Starting work on this

**Comment by HenrikJannsen** [comment]
Implemented with https://github.com/bisq-network/bisq-pricenode/pull/52
