### ISSUE TITLE
Ocorreu um erro ao inicializar o Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by HugxD** [bisq-network/bisq2#2177]
Ocorreu um erro ao inicializar o Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..
![erro bisq2](https://github.com/bisq-network/bisq2/assets/169672552/9edbedd8-1381-43bc-97d3-7793feb59e35)
[bisq erro.txt](https://github.com/bisq-network/bisq2/files/15294783/bisq.erro.txt)

I had BISQ2 2.0.3 open when my computer crashed. After restarting it, bisq started showing this error, I installed version 2.0.2 and it opens, but it gives an error when creating an offer! If you can check this I would appreciate it, as I need the service.

**Comment by HugxD** [comment]
When closing the program another error also appears

**Comment by HugxD** [comment]
Problem solved, I just ended up with another user. I renamed this folder

$home\AppData\Roaming\Bisq\

**Comment by HenrikJannsen** [comment]
Sometimes it helps to remove the tor directory inside the data directory. It should be also fixed with the upcoming release.
