### ISSUE TITLE
Reword warning popup for canceling a trade?

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2183]
I get several inquiries about canceling a trade when the peer is clearly unresponsive, and when I think it is okay to cancel because, for example, it's been a while without a reply by someone who would otherwise be expected to be at their screen right after taking an offer, I suggest they can cancel and provide proof of unresponsiveness if mediation is ever opened.
One user pointed out that the popup you get when trying to cancel after first data exchange happens, is quite threatening:

> Since the exchange of account details has begun, canceling the trade without the buyer's/seller's consent will be considered a violation of the trading rules and may result in your profile being banned from the network.

This also happens when the canceling party is the only one who shared his data, and should be able to decide if he doesn't care and cancel anyway.

So, my suggestion is to consider the situation above, and maybe include a notice that says "Since you were the only one to share your account details, rejecting the trade does not constitute a violation of the rules, but your peer will still be able to know your details [...] Are you sure you want to reject?"

For those situations where instead the peer has shared his data as well, and you want to cancel because of unresponsiveness, you can rephrase the start of the popup as "canceling the trade without the peer's consent **could** be considered a violation of the rules..." and then proceed to explain that, if the peer was unresponsive, canceling without a violation is a possibility. Maybe even make it dynamically determined, going by the time that passed since the last event in the trade.

**Comment by HenrikJannsen** [comment]
Wording has been improved in 2.1.0
