### ISSUE TITLE
Rename Bisq2 App: Remove Friction on MacOS Install

### ISSUE THREAD

**Issue by L0laL33tz** [bisq-network/bisq2#2192]
To run Bisq2 on MacOS, I have to bypass apple developer safeguards to get the app installed. On Bisq1, I do this via:

`sudo xattr -rd com.apple.quarantine /Applications/Bisq.app`

Bisq2 has a space in its application name, making it "Bisq 2.app". This screws up the path when adding to cmd line. I now have to either: rename the app manually, or add the path in quotes.

There's easy instructions to bypass apple developer safeguards on the internet, but this part can be hard to figure out for beginners unfamiliar dealing with paths or cmd line, adding unnecessary friction to install imo.

**By renaming the app file from 'Bisq 2.app' to 'Bisq2.app' that friction can be removed.** Happy to do a PR if someone tells me where to contribute.

**Comment by HenrikJannsen** [comment]
You can use a `\` before the space. But I agree its annoying and we should change it.

**Comment by HenrikJannsen** [comment]
Done with 2.1.0
