### ISSUE TITLE
Error: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port

### ISSUE THREAD

**Issue by AZmisc** [bisq-network/bisq2#2212]
Hi! When I launch Bisq 2 (B2) I get an error message asking me to create a new issue on this board and to upload the log file.

Here are screenshots of those error messages and the log file as well:

![b2_error_w01](https://github.com/bisq-network/bisq2/assets/47092625/71892428-e2ec-41d7-91c2-0c866d0e5266)
![b2_error_w02](https://github.com/bisq-network/bisq2/assets/47092625/4beb427a-8820-4690-8b71-da055ed67edf)
[bisq.log](https://github.com/bisq-network/bisq2/files/15387446/bisq.log)

I did manage to start B2 a handful of times. Then I started getting this message and can't get rid of it even if I uninstall and re-install B2. The issue persisted. 

It took removing the B2 folder from the Windows's Users folder to get rid of this error (but then the Java error kicked in which I will be submitting in due time).

Let me know if you need anything else.

**Comment by AZmisc** [comment]
Could completely cure this issue by deleting [Tor] folder from inside of [.../AppData/Roaming/Bisq2]

**Comment by thoeneberg** [comment]
The same was with me. Thanks for the help.

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
