### ISSUE TITLE
Unable to leave private chat error

### ISSUE THREAD

**Issue by techrivertree** [bisq-network/bisq2#2223]
A few weeks ago I completed a buy. I did not leave the private chat. I tried to leave today but I received the following error. After logging in here, Bisq 2 now says no private chats.

Also, why is there a reference to google?

![Screenshot from 2024-05-24 06-32-34](https://github.com/bisq-network/bisq2/assets/69227859/2fd864f4-fe02-4056-ab39-b9a83f404bf3)

Log

Github wont allow me to upload the log, prob because of the file size, 9.7Mb,

**Comment by HenrikJannsen** [comment]
This should be resolved by recent bug fixes
