### ISSUE TITLE
Include dominican peso (DOP), price tickers inside

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2230]
As per a user's request

https://www.coinbase.com/en-es/converter/btc/dop
https://www.xe.com/currencyconverter/convert/?Amount=1&From=DOP&To=BTC
https://cuex.com/en/btc-dop

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/bisq2/discussions/2310 for the problem about adding niche markets

**Comment by rodvar** [comment]
Starting work on this

**Comment by HenrikJannsen** [comment]
Implemented with https://github.com/bisq-network/bisq-pricenode/pull/52
