### ISSUE TITLE
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by Sniggly** [bisq-network/bisq2#2239]
[bisq2 issue.txt](https://github.com/user-attachments/files/15524091/bisq2.issue.txt)

**Comment by HenrikJannsen** [comment]
Could you also post the tor debug logs (from inside the tor directory)?

**Comment by Sniggly** [comment]
How do I navigate to the tor debug logs?

**Comment by HenrikJannsen** [comment]
At Settings/Utils you can open the data directory. There is a tor folder inside and there the debug.log
