### ISSUE TITLE
keep getting this error when i launch bisq 2

### ISSUE THREAD

**Issue by ialkeilani** [bisq-network/bisq2#2261]
An error occurred at initializing Bisq: bisq.tor.controller.exceptions.HsDescUploadFailedException: HS_DESC upload timeout triggered..

**Comment by HenrikJannsen** [comment]
Can you post the debug.log from the tor directory inside the data directory?
After posting that, can you try to delete the tor directory and start again?

**Comment by ialkeilani** [comment]
[debug.log](https://github.com/user-attachments/files/15614255/debug.log)

after closing and re-launching multiple times it eventually works

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
