### ISSUE TITLE
Notification bug in open trades view (annoying and wrong trade message)

### ISSUE THREAD

**Issue by ialkeilani** [bisq-network/bisq2#2266]
I keep getting this annoying and incorrect pop up message at the top in orange color:

New trade message for trade '5fb4cdc9' | Go to 'Open Trades'

When I click on it, it takes me to "My Open Trades" tab which is actually empty

I keep on clearing the message but it shows up within few seconds later again...

![image](https://github.com/bisq-network/bisq2/assets/6824858/a1f5067c-4aee-41f7-aa4d-c17cfa966d60)

**Comment by ialkeilani** [comment]
![image](https://github.com/bisq-network/bisq2/assets/6824858/b5d88fd9-b0f4-41dd-aa7b-45f91ffe3ca6)

**Comment by HenrikJannsen** [comment]
Its a known issue with notifications. You can reset it at Settings. Its on our long todo list...

**Comment by HenrikJannsen** [comment]
Should be resolved with latest bugfixes
