### ISSUE TITLE
Problem starting Bisq 2

### ISSUE THREAD

**Issue by CriptoRapport** [bisq-network/bisq2#2267]
I installed Bisq 2, I can't use it, because when it starts loading it gets stuck at 24% and after a while of loading the following error appears. The bisq.log file from bisq 2 is also attached to analyze the possible error!

![Tela Erro Bisq 2](https://github.com/bisq-network/bisq2/assets/171962967/59359099-8807-47b9-a35b-5669763f5f31)

[bisq.log](https://github.com/user-attachments/files/15659109/bisq.log)

**Comment by HenrikJannsen** [comment]
Can you post alse the tor debug.log (in tor folder)?

**Comment by CriptoRapport** [comment]
This file is not appearing in the Bisq 2 folder. See the tor folder in the screenshot.
![Pasta Bisq 2](https://github.com/bisq-network/bisq2/assets/171962967/16d0705d-e95d-40f2-92ed-490e6f86a41f)

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
