### ISSUE TITLE
How to run a custom path and build with this argument? --data-dir=/files/Bisq2Data with the standard command ./gradlew desktop:desktop-app:run

### ISSUE THREAD

**Issue by thiagopaesm** [bisq-network/bisq2#2278]
How to run custom path in ./gradlew desktop:desktop-app:run ?

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :desktop:desktop
Project :desktop => no module-info.java found

> Configure project :desktop:desktop-app
Project :desktop-app => no module-info.java found

> Configure project :desktop:desktop-app-launcher
Project :desktop-app-launcher => no module-info.java found

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :desktop-app:run from command line.
> Unknown command-line option '--data-dir'.

* Try:
> Run gradlew help --task :desktop-app:run to get task usage details.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
39 actionable tasks: 39 up-to-date

**Comment by HenrikJannsen** [comment]
Which java version do you use? Bisq requires JDK 17.
See readme.md for run instructions...
E.g. `apps/desktop/desktop-app/build/install/desktop-app/bin/desktop-app --data-dir=<data_dir>`

**Comment by thiagopaesm** [comment]
> Qual versão java você usa? Bisq requer JDK 17. Consulte readme.md para instruções de execução... Por exemplo`apps/desktop/desktop-app/build/install/desktop-app/bin/desktop-app --data-dir=<data_dir>`

Thank you for the information. It's strange that I can run the code with ./gradlew desktop:desktop-app:run even though my Java version is different from 17. This folder install is empty here... 

/bisq2$ ./gradlew build                                   
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :desktop:desktop
Project :desktop => no module-info.java found

> Configure project :desktop:desktop-app
Project :desktop-app => no module-info.java found

> Configure project :desktop:desktop-app-launcher
Project :desktop-app-launcher => no module-info.java found
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 36s
Need update java
