### ISSUE TITLE
Tor control port error (renamed from "opening issues")

### ISSUE THREAD

**Issue by rich1948** [bisq-network/bisq2#2287]
![Screenshot 2024-06-11 154829](https://github.com/bisq-network/bisq2/assets/172367309/e8f0062b-6137-45a2-b55c-89dcc9a70369)
anyone know how to solve this ?

**Comment by HenrikJannsen** [comment]
Which version do you use?
Can you post the debug.log from the tor directory (inside the data directory, can be opened in Settings/Utils)

**Comment by yuvrajsaraogi** [comment]
The error message you're encountering indicates that Bisq is unable to connect to the Tor control port. This is often related to issues with the Tor network configuration or the Tor service itself. Here are some steps you can take to troubleshoot and resolve this issue:

Check Tor Installation: Ensure that Tor is installed and running properly on your system. If it's not installed, you may need to install it first.

Restart Tor: Sometimes, simply restarting the Tor service can resolve connection issues. You can restart Tor by stopping and then starting the service.

Check Tor Configuration: Ensure that the Tor configuration file (torrc) is set up correctly. The control port should be configured, and the necessary authentication methods should be enabled.

Firewall/Antivirus: Check if your firewall or antivirus software is blocking the connection to the Tor control port. If so, you may need to create an exception for Tor and Bisq.

Network Issues: Ensure that your network allows Tor connections. Some networks might block Tor traffic, which can prevent Bisq from connecting to the control port.

Log Files: Review the log files for more detailed error messages. The log file can provide specific information about what might be causing the connection issue.

Update Bisq and Tor: Ensure that you are using the latest versions of Bisq and Tor. Sometimes, updating to the latest version can resolve compatibility issues.

Configuration Settings in Bisq:

Open Bisq.
Go to Settings -> Network Info.
Check the Tor settings and ensure they are correct. You might need to manually set the Tor control port and the authentication method if they are not automatically detected.
Example Tor Configuration (torrc)
Make sure your torrc file includes the following lines:

plaintext
Copy code
ControlPort 9051
CookieAuthentication 1
Steps to Restart Tor on Different Operating Systems:

On Windows:

Open the Services management console (services.msc).
Locate the Tor service.
Right-click and select Restart.

On macOS:

brew services restart tor

If these steps do not resolve the issue, you might want to report the bug as suggested in the error message, including the log file for further assistance from the Bisq development team.

**Comment by yuvrajsaraogi** [comment]
The error message you're encountering indicates that Bisq is unable to connect to the Tor control port. This is often related to issues with the Tor network configuration or the Tor service itself. Here are some steps you can take to troubleshoot and resolve this issue:

Check Tor Installation: Ensure that Tor is installed and running properly on your system. If it's not installed, you may need to install it first.

Restart Tor: Sometimes, simply restarting the Tor service can resolve connection issues. You can restart Tor by stopping and then starting the service.

Check Tor Configuration: Ensure that the Tor configuration file (torrc) is set up correctly. The control port should be configured, and the necessary authentication methods should be enabled.

Firewall/Antivirus: Check if your firewall or antivirus software is blocking the connection to the Tor control port. If so, you may need to create an exception for Tor and Bisq.

Network Issues: Ensure that your network allows Tor connections. Some networks might block Tor traffic, which can prevent Bisq from connecting to the control port.

Log Files: Review the log files for more detailed error messages. The log file can provide specific information about what might be causing the connection issue.

Update Bisq and Tor: Ensure that you are using the latest versions of Bisq and Tor. Sometimes, updating to the latest version can resolve compatibility issues.

Configuration Settings in Bisq:

Open Bisq.
Go to Settings -> Network Info.
Check the Tor settings and ensure they are correct. You might need to manually set the Tor control port and the authentication method if they are not automatically detected.
Example Tor Configuration (torrc)
Make sure your torrc file includes the following lines:

plaintext
Copy code
ControlPort 9051
CookieAuthentication 1
Steps to Restart Tor on Different Operating Systems:
On Linux:

sudo systemctl restart tor
On Windows:
Open the Services management console (services.msc).
Locate the Tor service.
Right-click and select Restart.
On macOS:

brew services restart tor

If these steps do not resolve the issue, you might want to report the bug as suggested in the error message, including the log file for further assistance from the Bisq development team.

**Comment by charlee-dr** [comment]
Same issue here, cannot open Bisq2 at all... "A problem occurred initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port.."

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory inside the Data directory?

**Comment by charlee-dr** [comment]
Great, this has worked! Thank you. The only problem is that I have to do the same every time I close Bisq2.

**Comment by HITH00** [comment]
Can you please reexplain how to fix this and how to delete the tor directory inside the data directory. Would be very much appreciated. Thanks

**Comment by HenrikJannsen** [comment]
For Bisq 1 yo can find here about data directory locations: https://bisq.wiki/Data_directory

Bisq 2 is at same location but directory is named Bisq2. Navigate inside that folder and delete the tor folder. Do not delete the tor folder in Bisq 1 as it contains the key for the onion address! In Bisq 2 that key is not stored in the tor folder.

**Comment by HITH00** [comment]
I deleted both the tor and the torcommon folder and now it just says "Failed to launch JVM". Please help

**Comment by HenrikJannsen** [comment]
Where have you deleted that? I assume you did it in the application directory not the data directory. `torcommon` is not part of the data directory. You need to undo that or re-install Bisq if you deleted it from the app directory. The tor dir inside the data dir looks on MacOS like:
![Screenshot 2024-07-29 at 11 37 30](https://github.com/user-attachments/assets/7a0bc03c-b8d2-4aa5-b2f7-61759f54354e)

**Comment by HenrikJannsen** [comment]
See https://bisq.wiki/Data_directory about locations. For Bisq 2 its the Bisq 2 or Bisq2 folder

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
