### ISSUE TITLE
Button order of reputation build up should match list

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#2308]
Right now the order of the buttons does not match the list above.

![Bildschirmfoto 2024-06-18 um 10 33 39](https://github.com/bisq-network/bisq2/assets/150681275/299c0016-6693-4249-9a0b-d13340d386be)

I'll push this fix in a PR soon

**Comment by HenrikJannsen** [comment]
The buttons have the right order (higher impact to lower)

**Comment by hiciefte** [comment]
> The buttons have the right order (higher impact to lower)

Then probably we should just change the list

**Comment by hiciefte** [comment]
Like that

![Bildschirmfoto 2024-06-18 um 10 48 41](https://github.com/bisq-network/bisq2/assets/150681275/eb8ae3c4-39bb-44a4-b1c4-b60ac119e7f9)
