### ISSUE TITLE
Create Open timestamp service

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#231]
For secure timestamping we should add a OTS service (https://opentimestamps.org/).
This would be useful for providing proof of date when an identity was created and could serve as some form of reputation (e.g. one could assume users who have created their identity long time ago that they are not scammers).
It is similar to the account age feature in Bisq but with OTS we would be getter security. 
It does not need to be very senistive to exact time but a one day tolerance would be ok for the intended use case.

Instead of publishing the time stamp data to the P2P network as we did in Bisq 1 we could exchange it only on demand between peers. So first a user trust that the peer is not lying about their identity/account age but once they enter any private communication (trade, chat) they exchange the OTS proof and it can be verified. This helps to avoid to flood the P2P network storage wiht lot of data.  

The connection to the OTS service should be possible over Tor and I2P. If that is an issue with existing services we could run our own and expose Tor and I2P access.

Any dev interested to work on that? It is not high prio but would be a nice to have and adds more option for forms of reputation.

**Comment by alkum** [comment]
Interested.

**Comment by c4talys7** [comment]
I'm interested in this topic @chimp1984.

**Comment by chimp1984** [comment]
Completed by @c4talys7 with https://github.com/bisq-network/bisq2/pull/372
