### ISSUE TITLE
Light theme option

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2314]
I know perfectly how tight is the development schedule on Bisq2.
Yet it's been now more than a few times that users have directly inquired about a light theme in bisq2 (oh, the horror, I know!), so I thought I could just put this down here in case maybe some new dev wants to try his hands with this?

**Comment by HenrikJannsen** [comment]
I am pretty sure that we will not work on that as its too much work and maintaining 2 themes will add constant extra effort. We see in Bisq 1 how badly the themes are maintained. Better have on theme which is polished than 2 themes with lot of imperfections.
