### ISSUE TITLE
Initialising applicationService failed.

### ISSUE THREAD

**Issue by Greengoblin007** [bisq-network/bisq2#2333]
I just formatted my PC but made a backup obviously. Now when I copy that backup to the default folder, Bisq2 does not initialise, it says:

**Bisq: bisq.tor.controllerCommandFailedException: Coundn't connect  to control port.**

What can I do?

Thank you and regards!

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by HenrikJannsen** [comment]
Have you tried a restart?

**Comment by Greengoblin007** [comment]
> Have you tried a restart?

Yes, I just rebooted my PC but to no avail, the problem persists.

Regards

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory inside the data directory?

**Comment by Greengoblin007** [comment]
> Can you try to delete the tor directory inside the data directory?

Yes, that worked like a charm.

Thanks!
