### ISSUE TITLE
Add BIP21 QR codes for bitcoin addresses

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#2361]
From a user's message, which I found interesting:

> Would it be possible to add BIP21 qr codes? To make it easier to use mobile app wallets for example... https://github.com/bitcoinibips/blob/master/bip-0021.mediawiki

**Comment by HenrikJannsen** [comment]
Link is broken.

**Comment by HenrikJannsen** [comment]
QR code display and scan via webcam is implemented now. If anyone can test on different environments would be good.

I dont see much value to add the BIP 0021 URI Scheme.
