### ISSUE TITLE
Integrate XMR-BTC cross-chain atomic swap 

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#237]
We are looking for a developer who integrates the farcaster-project XMR-BTC cross-chain atomic swap project [1] into Bisq 2.

Rough concept is to rebuild the functionality of the CLI in java and add that as module in Bisq 2. Start up the required infrastructure (daemon, block chain nodes) and implement the API communication to the daemon. 

The developer should have some cryptographic background, should be familiar with Rust, Java, Monero and Bitcoin. 
 
[1] https://github.com/farcaster-project/

**Comment by alvasw** [comment]
If this task is free after I'm done with electrum. I'd like to work on this.
