### ISSUE TITLE
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by throwaway906** [bisq-network/bisq2#2391]
### Description

An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

#### Version

bisq2 2.0.4

### Steps to reproduce

1. Click on Bisq2 to start it.
2. Get the error.

### Expected behaviour

Actually connecting me to Bisq2.

### Actual behaviour

An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

#### Device or machine

Windows 11 Pro
[Uploading bisq error log.txt…]()

[Uploading bisq error log.txt…]()

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory inside the bisq2 data directory?

**Comment by ordinary-github-user** [comment]
not op
same problem
but deleting C:\Users\username\AppData\Roaming\Bisq2\tor worked
