### ISSUE TITLE
v2.0.5: Mediation messages are passed to Resource Bundle for translation

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#2470]
Mediation messages are passed to resource bundle for translation which results in developer mode in a warning message
```
11:46:09.133 ERROR [JavaFX Application Thread] b.i18n.Res: Missing resource for key: Your trade peer requested mediation support. I am a registered Bisq mediator. I am here to help you both to resolve any issues. 
```

Unfortunately my debugger somehow is not able to connect, so I wasn't able to find the root cause easily.

**Comment by hiciefte** [comment]
Probably not related to it, but who knows. Now after opening a new mediation somehow the messages are doubled (peers) or tripled (mediator) for the user. The receiver only sees it once.

![Bildschirmfoto 2024-07-23 um 11 54 31](https://github.com/user-attachments/assets/f34344d2-ffb8-495e-8b34-949a58b570cb)

![Bildschirmfoto 2024-07-23 um 11 55 23](https://github.com/user-attachments/assets/c273d5e6-b386-4219-8937-bf3b6e3a00db)

**Comment by HenrikJannsen** [comment]
Did you test with new version and latest commits? I just added a fix in that area for trade log messages. Have not tested mediation messages.
Do you have any old node/seed running as well or only new nodes? the duplication might be caused by old nodes having another hash for same message.

**Comment by HenrikJannsen** [comment]
With recent PRs those issues should be resolved.
