### ISSUE TITLE
Initialising applicationService failed.

### ISSUE THREAD

**Issue by graffitisnap** [bisq-network/bisq2#2512]
![image](https://github.com/user-attachments/assets/61044af8-4048-488f-b8da-71923faf2020)
![image](https://github.com/user-attachments/assets/b238f31b-b40b-4059-9284-abac8874e3d5)
fresh reinstall does not work
[bisq.log](https://github.com/user-attachments/files/16405126/bisq.log)

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory inside the data directory?

**Comment by Langestrand** [comment]
I have the same issue on a windows pc. 

i cant find any tor directory. Where is it? 

bg

**Comment by HenrikJannsen** [comment]
https://bisq.wiki/Data_directory

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
