### ISSUE TITLE
Add ProGuard to decrease Bisq file size and potentially improve performance

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#2522]
Any dev experienced with ProGuard and interested to add it to our gradle build?

**Comment by rodvar** [comment]
@HenrikJannsen starting work on this one

**Comment by HenrikJannsen** [comment]
The work on that has been conserved in https://github.com/bisq-network/bisq2/tree/Proguard-support but it got dropped so far as the reduction was not as big as hoped and did not justify the added complexity and risks.
