### ISSUE TITLE
Add the git commit version as 4th token to the version 

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#2532]
It would be useful to know exactly which version the binary was built from by including the truncated commit hash to the version.

This should not be shown in normal display context, but only in logs and in Settings/Util as detail info about the  version.

**Comment by rodvar** [comment]
@HenrikJannsen can help with this. Could you share how exactly the prod build is generated (or the docs link if there is any?) 
I'll make sure the build version grasps the truncated version of the hash.

Format would be something like `2.1.0-[TRUNCATED_HASH]` that sounds good?

**Comment by HenrikJannsen** [comment]
In DesktopAppLauncher there is the generateInstaller gradle task. 

I think its best to add a `commitHash` field to the Version class and keep it separated from semantic versioning.
We could even create a new class for it where we provide that commitHash.

For display purpose we can see then whats fits best. In the Utils UI maybe: `Version: 2.1.0; built on commit hash: 123abc` with a link to the GH commit.

In logs we also can separate it like that.

It would be just useful to know which commit hash an app is running, specially for non-user apps like seed nodes, etc. We could include that then in future monitoring to see which nodes have updated. Those headless infrastructure nodes do not always follow release cycles.

**Comment by rodvar** [comment]
> In DesktopAppLauncher there is the generateInstaller gradle task.
> 
> I think its best to add a `commitHash` field to the Version class and keep it separated from semantic versioning. We could even create a new class for it where we provide that commitHash.
> 
> For display purpose we can see then whats fits best. In the Utils UI maybe: `Version: 2.1.0; built on commit hash: 123abc` with a link to the GH commit.
> 
> In logs we also can separate it like that.
> 
> It would be just useful to know which commit hash an app is running, specially for non-user apps like seed nodes, etc. We could include that then in future monitoring to see which nodes have updated. Those headless infrastructure nodes do not always follow release cycles.

sounds great, let's keep VERSION clean and we just add the COMMIT_HASH to the BuildVersion generated class, then each software component can use it as needed.

I'll have a look also into the "Utils UI" comment when I tackle this one, thanks!

**Comment by rodvar** [comment]
Starting work on this :rocket:
