### ISSUE TITLE
Market items show a badge when there are no offers

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#2577]
It seems that market items show a badge for expired offers. I only see this issue when scrolling down.

![image](https://github.com/user-attachments/assets/9c70f3e6-78b2-4f81-9565-880eef22f8c1)

**Comment by namloan** [comment]
Some clarifications:

* Scrolling wasn't related at all. The only condition was to get a notification in a channel that is not selected.
* Only happened with text messages. Offers worked OK.
* Happens for messages that are expired or actively removed.
