### ISSUE TITLE
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by pKavs** [bisq-network/bisq2#2596]
Whenever I launch Bisq 2 on Windows I am unable to connect and get this error almost immediately on launch

**Comment by strayorigin** [comment]
The workaround at the moment is to delete or rename the 'tor' folder in the bisq 2 data directory.

**Comment by HITH00** [comment]
Strayorigin i think we would all really appreciate if you could please type out a step by step tutorial on how to delete the tor folder in the bisq directory. If you can

**Comment by strayorigin** [comment]
You would first need to navigate to the default data dir for bisq 2:

Windows Power Shell: $home\AppData\Roaming\Bisq2\
Windows Cmd (or Win+R): %USERPROFILE%\AppData\Roaming\Bisq2\
Mac: /Users/<username>/Library/Application Support/Bisq2/
Linux: /home/<username>/.local/share/Bisq2/

Within that you will see a folder called 'tor'
According to the devs it should be safe to delete this folder in Bisq 2, however, I prefer to just rename it to something like 'tor-MMDDYY' just in case I need to restore for whatever reason.

**Comment by HITH00** [comment]
Really appreciate that. Finally found the directory.

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
