### ISSUE TITLE
Initialising aplicacionServise failed

### ISSUE THREAD

**Issue by demiandreu** [bisq-network/bisq2#2619]
I can't open the application, it tells me: Initialising applicationService failed. Does anyone know how to fix this? Thanks

**Comment by demiandreu** [comment]
<img width="618" alt="adfsdfgdgfdg" src="https://github.com/user-attachments/assets/8bb479d5-cd15-4f5d-b909-6ffc634d1403">

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@demiandreu 
Best Regards.

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
