### ISSUE TITLE
PYG fiat currency (Paraguay currency)

### ISSUE THREAD

**Issue by HostFat** [bisq-network/bisq2#2645]
I've just installed the Bisq v2.1.0, and I see that PYG fiat currency isn't enabled.

Can you enable it with the next version? (v2.1.1)

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/bisq2/discussions/2310 for the problem about adding niche markets

**Comment by HostFat** [comment]
Can this be useful?

https://yadio.io/api.html
https://api.yadio.io/exrates

**Comment by HenrikJannsen** [comment]
Currently we don't have dev resources to work on new integrations. If you are interested or know someone please contribute. https://github.com/bisq-network/bisq-pricenode is the repo

**Comment by rodvar** [comment]
@HenrikJannsen I'm happy to work on this at some point this month, I've done pricenode work in the past so should be quite straightforward for me

**Comment by HenrikJannsen** [comment]
I guess you have read the discussion here: https://github.com/bisq-network/bisq2/discussions/2310

**Comment by rodvar** [comment]
> I guess you have read the discussion here: #2310

@HenrikJannsen 
I did, to your comments there for Argentina we do have a solution in place, that was exactly my first contribution to Bisq :D .

The APIs suggested by @HostFat go inline with the discussion, they give you the current USD/BTC rate and USD/[Marginal_currency] rates so you can simply multiply to get some prices for our pricenodes.

Not sure if we wanna take the opportunity to get other countries rates in, but at least for PYG - there are no currency controls (like there are in Argentina, Venezuela, Lebanon, etc) so a solution like this one should work.

**Comment by HenrikJannsen** [comment]
I think it would be good to get the other requested currencies in as well.  See https://github.com/bisq-network/bisq2/labels/pricefeed . But can be done one by one...

**Comment by rodvar** [comment]
Starting work on this

**Comment by HostFat** [comment]
@rodvar if you are able to add the support for all the other currency available in Yadio, it will be an huge improvement, there will then many more customers from all those countries :)

**Comment by rodvar** [comment]
Hi @HostFat !

We've added Yadio API to support our pricenodes now so as pricenode admins start to upgrade you should see the prices in Bisq 1 & 2.

Initially we are just using the specifically requested currencies (PYG, BOB, EGY, DOP) we have in our github issues + we added LBP as it has been requested in the past and another pricepoint for the currently available ARS since the rate is blue.

The implementation we've done on Yadio makes it easy to add more currencies in, in the future as we see interest in them.
Hope this all helps, cheers!

**Comment by HostFat** [comment]
I've installed now the V2.1.2, but I can't see the possibility to open trades in PYG fiat value.

I can't see it on both Create offer -> Buy / Sell Bitcoin.

**Comment by rodvar** [comment]
@HenrikJannsen funny, I was about to ask you the same thing haha The code was merged so its a matter of knowing which version of the seednode the nodes are running. I'll ask in the matrix room now.

**Comment by rodvar** [comment]
just to confirm to everyone, I've just downloaded price node latest code and ran it locally with the provided `bisq-pricenode` script, I can see Yadio pricepoints including BTC/PYG at the time of writing 1BTC ~= 540M PYG
![Screenshot from 2024-10-25 13-28-06](https://github.com/user-attachments/assets/78a3234f-a7ea-4956-97ef-c0e2889f590e)

**Comment by HostFat** [comment]
Well, in the interface I can't create offers with PYG, I guess that then other fiat currencies are missing.

**Comment by rodvar** [comment]
@HostFat yep we are trying to figure out what's going on, we'll let you know!

**Comment by HenrikJannsen** [comment]
@rodvar Can you try to point your local bisq2 app to your own price node which provide PYG? To verify that from Bisq 2 side there is no issue...

**Comment by rodvar** [comment]
@HostFat we have a fair amount of pricenodes updated now, I can see already the market prices coming in my Bisq2 instance, can you?

![Screenshot from 2024-10-26 20-07-22](https://github.com/user-attachments/assets/51929ee4-5aa0-4faa-a542-35b413f92ff7)

**Comment by HostFat** [comment]
Yes it works now, good and thanks :)
