### ISSUE TITLE
Sending Take-Offer Message hangs until "Report Bug" pop-up opens

### ISSUE THREAD

**Issue by augustspring19** [bisq-network/bisq2#2648]
As per the title, if I try to make an offer on any trade, it will be stuck on the "Sending Take-Offer Message" loading page until the error pops up. I've attached 3 logs of 3 separate trades I have tried to request all resulting in the same error.

After closing the error message, if I go to my open offers, I can see the requests all there - I can proceed with adding my wallet info which seems normal, however looking closer all of the parts of the trade on my end seem to be stuck on "Connecting to peer" (sending the bitcoin address or sending a chat dm). I have no issues sending messages in Discussions/Support, or any issues seeing trades in the offerbook.

Any advice or troubleshooting help would be massively appreciated!

[bisq.log](https://github.com/user-attachments/files/16660314/bisq.log)
[bisq2.log](https://github.com/user-attachments/files/16660399/bisq2.log)
[bisq3.log](https://github.com/user-attachments/files/16660401/bisq3.log)

**Comment by HenrikJannsen** [comment]
Hm... I just tried 2 self trades with peer being online and offline and both worked. Have you tried to restart your app?
There might be an issue that the socket timeout is longer than the send take-offer message timeout (2 min), I will look into that, but have never experienced that while testing. Usually if the peer is offline the connection fails quickly and then the message is sent as mailbox message to the network.

**Comment by augustspring19** [comment]
Restarted the app and tried again, it worked this time. The offer I cancelled that did not process to begin with has disappeared from my "Open Trades," however when I go to offer it again, it shows a pop-up that says "You have already taken this offer" - despite not showing in my "Open Trades" and having successfully cancelled before. 

I restarted the client again and it still persists. It's fine, I can take another offer instead, but I figured it was worth saying this also happened.

At least the new one went through immediately! Sending the wallet address now shows "Message receipt acknowledged" - I can't remember how long I had the client open before to cause this unfortunately.

**Comment by HenrikJannsen** [comment]
> however when I go to offer it again, it shows a pop-up that says "You have already taken this offer" - despite not showing in my "Open Trades" and having successfully cancelled before.

Yes thats by design. You cannot take the same offer twice even in failures.
