### ISSUE TITLE
Bisq2 hangs during startup, then shuts down with error

### ISSUE THREAD

**Issue by ChanoSan** [bisq-network/bisq2#2653]
Bisq2 v2.1.0, running on Ubuntu 20.04.6 LTS (focal)

On startup, Bisq2 begins "Initialize P2P Network" / "Bootstrap to Tor network", but hangs at 24%. After a few minutes of inactivity, it displays the following error message:

```
Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.5.15.0-117-generic
Error message:
An error occurred at initializing Bisq: java.util.concurrent.TimeoutException.
```

This has occurred multiple times, and as yet Bisq2 cannot successfully start, but always shuts down in error.

Log files provided are as follows:

[bisq2_log.txt](https://github.com/user-attachments/files/16667477/bisq2_log.txt)

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor directory inside the data directory?

**Comment by ChanoSan** [comment]
> Can you try to delete the tor directory inside the data directory?

This would be /home/.local/share/Bisq2/tor , is that right?

**Comment by ChanoSan** [comment]
Assuming that was the correct location, deleted it and restarted the application, but the same behaviour occurred.

**Comment by HenrikJannsen** [comment]
Yes, thats the location. Hm...weird. Can you try to backup your data directory and start with a completely fresh one? Have not heard of anyone else with that issue. Can you try also before if tor browser works or Bisq1 if you have that installed? Also try to restart the OS, sometimes processes hang or ports are blocked.

**Comment by ChanoSan** [comment]
Attempted the following:
- Rebooted the computer and then started Bisq 2
- Uninstalled and then reinstalled Bisq-2.1.0 deb package, then started Bisq 2

In both cases, the same error persisted.

Trying out Tor Browser was one of the first things I checked, and that works fine. Bisq1 also starts and runs normally (Haveno also works, for that matter).

Basically, every other process that needs to run a Tor process works as expected. The error appears to be isolated to Bisq2, but I'm not sure how, where, or why.

Can provide more logs, or run more test cases on request.

**Comment by HenrikJannsen** [comment]
Can you provide the tor debug log file from inside the tor folder?
Have you tried with a fresh data directory? 
@alvasw Do you have any idea?

**Comment by ChanoSan** [comment]
> Can you provide the tor debug log file from inside the tor folder? 
I'm looking in the tor folder, but currently no debug log file is visible. I'm not sure why.

I'll try deleting the data directory after uninstall, then reinstall and try again. See if that shakes anything loose.

**Comment by ChanoSan** [comment]
I ran `dpkg -P bisq2` to uninstall and purge all config files, then manually deleted the bisq2 directory in /.local/share/ before reinstalling Bisq2 and trying again.

There is no change, the same error occurs. In the interests of being thorough, this is the new bisq.log:

[bisq.log](https://github.com/user-attachments/files/16685641/bisq.log)

**Comment by HenrikJannsen** [comment]
@alvasw Could you have a look to the logs? Its very short. It does not get beyond:
```
TorTransportService: Initialize Tor 
TorInstaller: Tor files installed to <HOME_DIR>/.local/share/Bisq2/tor 
```

**Comment by HenrikJannsen** [comment]
@ChanoSan In case you are a dev and familiar with IntelliJ you could try to debug it to see where it hangs. A good etnry point would be TorInstaller where it logs "Tor files installed to...". If you set a breakpoint there and keep stepping through it might reveal where it fails.
I have not heard from such an issue with 2.1.0 so far. So it seems it some local issue or some rare edge case.

**Comment by Tobiasheitor** [comment]
> Bisq2 v2.1.0, running on Ubuntu 20.04.6 LTS (focal)
> 
> On startup, Bisq2 begins "Initialize P2P Network" / "Bootstrap to Tor network", but hangs at 24%. After a few minutes of inactivity, it displays the following error message:
> 
> ```
> Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
> Operating system: linux / x86_64 / 64 v.5.15.0-117-generic
> Error message:
> An error occurred at initializing Bisq: java.util.concurrent.TimeoutException.
> ```
> 
> This has occurred multiple times, and as yet Bisq2 cannot successfully start, but always shuts down in error.
> 
> Log files provided are as follows:
> 
> [bisq2_log.txt](https://github.com/user-attachments/files/16667477/bisq2_log.txt)

I'm having the same issue

**Comment by ChanoSan** [comment]
@HenrikJannsen 
> In case you are a dev and familiar with IntelliJ you could try to debug it to see where it hangs

Unfortunately I'm not, so I'll just have to hope it can be figured out eventually

**Comment by rodvar** [comment]
From the logs above is timeouting connecting to a tor relay, hangs at 14%

```
25 21:40:30.776 [Thread-43] INFO  b.t.c.BootstrapService: Tor bootstrap event: BootstrapEvent(progress=14, tag=handshake, summary=Handshaking with a relay" WARNING="DONE" REASON=DONE COUNT=74 RECOMMENDATION=warn HOSTID="EE2A621042994B29452C12FF3B6F62D9E957758C" HOSTADDR="145.239.41.102:9001,

bisq.tor.controller.exceptions.TorBootstrapFailedException: Could not bootstrap Tor in 240 seconds
```

I'm unsure is this is the same reason for the original discussed issue.

But generally speaking: Do you have control on the network you are running Bisq2? 
I wonder if you are getting any direct Tor connection ports or address blocked in your network?

Testing tor on a browser might not be enough to guarantee Bisq is gonna work I think, a better test would be running Bisq1 to see if you get the same problem / get more log data to try to find what's going on.

Would you mind trying downloading the source code and running from there? It would be something like the following on a Linux Terminal:

```
 $ git clone https://github.com/bisq-network/bisq2.git  // optionally [download a zip](https://github.com/bisq-network/bisq2) and unzip in your preferred folder and go to that folder in the terminal
 $ cd bisq2
 $ ./gradlew buildAll
 $ ./apps/desktop/desktop-app-launcher/build/install/desktop-app-launcher/bin/desktop-app-launcher
```

you will see logs in the terminal whilst the app launches and tries to connect to Tor.

**Comment by qv4** [comment]
> > Bisq2 v2.1.0, running on Ubuntu 20.04.6 LTS (focal)
> > On startup, Bisq2 begins "Initialize P2P Network" / "Bootstrap to Tor network", but hangs at 24%. After a few minutes of inactivity, it displays the following error message:
> > ```
> > Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
> > Operating system: linux / x86_64 / 64 v.5.15.0-117-generic
> > Error message:
> > An error occurred at initializing Bisq: java.util.concurrent.TimeoutException.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This has occurred multiple times, and as yet Bisq2 cannot successfully start, but always shuts down in error.
> > Log files provided are as follows:
> > [bisq2_log.txt](https://github.com/user-attachments/files/16667477/bisq2_log.txt)
> 
> I'm having the same issue. Here is my logs: [bisq.log](https://github.com/user-attachments/files/16742701/bisq.log) [debug_for_zip.log](https://github.com/user-attachments/files/16742703/debug_for_zip.log)

Same issue here as well.

**Comment by qv4** [comment]
Sorry for the lack of detail. Pretty much tried the same steps: purging, reinstalling, making sure Java SDK 22 is installed, etc. Application times out at 24% every time, with the above error. Ubuntu 20.04

**Comment by ChanoSan** [comment]
Just as a side note, I tried a fresh install on Ubuntu Jammy (22.04) and it ran as expected.

Based on @qv4 's input, I feel like Ubuntu Focal (20.04) is the common factor.

**Comment by rodvar** [comment]
Thanks for that insight, that narrows down the issue.

I have a PC with Ubuntu 24.04.1 LTS and it runs great.

Quick search on tor related issues for that specific Ubuntu version brought me to this:

 - https://askubuntu.com/questions/1277817/is-tor-browser-installation-broken
 
 does this sounds familiar to you guys? 

I guess asking anyone to upgrade to a newer LTS version to use Bisq is too much to ask :) , but also as Henrik said we are way too busy and low on resources to focus on an issue on a very specific Ubuntu version.

If I get some spare time this month I'll get a virtual machine with Ubuntu 20.04 and try to repro this locally

**Comment by ChanoSan** [comment]
I've been using Tor-based processes in Focal for some time, with no issue, but on reflection I've never used it from paclage manager. My Tor Browser is a standalone program downloaded from TorProject, I use an OnionShare Snap package with embedded Tor, etc.

I have been able to run bisq1 on Focal with zero problems, but I don't know if that uses an embedded tor process or relies on system tor... I'm wagering a guess bisq1 & bisq2 and handling tor connections differently, but I can only speculate.

For now I guess I'll stick to using bisq2 on Jammy.

**Comment by rodvar** [comment]
Bisq do package the Java Tor library.

Thank you @ChanoSan , Bisq2 is the way to go as all our efforts are mostly there at the moment and once we get multisig trading working on Bisq2 (which is on the way), Bisq1 trading will most likely be discontinued.

**Comment by ChanoSan** [comment]
> Hi @ChanoSan, a shared library required by Tor seems to be missing on your operating system. I'm working on a fix for your problem.
> 
> As a workaround you can install Tor on your operating system using the package manager. The package manager will automatically install the missing shared libraries.
> 
> ```
> sudo apt-get install tor
> ```
> 
> Could you please report back if this solves your problem?
> 
> Thank you!

Attempting to install tor via cli returns a message that it's already installed:
`tor is already the newest version (0.4.2.7-1).`

However, I realized my system is using whatever version of Tor is available through standard repositories, and these are almost certainly out of date. So I switched to the Tor Project repo [as recommended on their page](https://support.torproject.org/apt/tor-deb-repo/), and attempted to run Bisq2 again once up to date.

This time, startup completed successfully and Bisq2 could start. So thank you for this, it seems to resolve the problem.
