### ISSUE TITLE
Bisq2 faults after entering text into any field

### ISSUE THREAD

**Issue by satscoffee** [bisq-network/bisq2#2666]
When I type a character into any field, I get a bug report pop up. It happens during the Create your Profile and any time I try to type anything into the program. Details of the bug are below and logs are in pastebin link. 

Of note, when I was checking installation, I did not see any jar files installed at /Applications/Bisq.app/Contents/Java/ 

And actually there is not even a "Java" folder within "Contents". The only files in Content are below:
.		Info.plist	PkgInfo		_CodeSignature	runtime
..		MacOS		Resources	app

First entry in the logs is: 
Aug-21 14:42:08.955 [main] INFO  b.d.DesktopAppLauncher: No jar file found. Run default Bisq application with version 2.1.0 

Bug details:
Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: macos / x86_64 / 64 v.14.6.1
Error message:
java.lang.StringIndexOutOfBoundsException: Range [1, 2) out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
	at java.base/java.lang.String.substring(String.java:2876)
	at com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(MacAccessible.java:1853)

My logs: https://pastebin.com/AEkfP3eX

**Comment by HenrikJannsen** [comment]
Hm... weird...

Its caused in `com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(MacAccessible.java:1853)` but as the stacktrace does not go further back I don't see from where its called from our code. 
I debugged with a breakpoint in it (but I have a aarch64 mac so might behave different to the intel), but did not enter to that method.
Which screen did you use or which activity did you do when the error appeared?

**Comment by satscoffee** [comment]
It happens in almost every text entry field. Also happens now in Bisq original for most text entry fields. I noticed this starting some version ago can’t recall which. Noticed again in Bisq2 when setting up a profile name - first screen. Also happens when adding payment methods or trying to type a message. On Aug 23, 2024, at 07:39, HenrikJannsen ***@***.***> wrote:﻿
Hm... weird...
Its caused in com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(MacAccessible.java:1853) but as the stacktrace does not go further back I don't see from where its called from our code.
I debugged with a breakpoint in it (but I have a aarch64 mac so might behave different to the intel), but did not enter to that method.
Which screen did you use or which activity did you do when the error appeared?

**Comment by HenrikJannsen** [comment]
Do you have anything special enabled/disabled in Accessibility?

Here is a related bug report when using voicover: https://bugs.openjdk.org/browse/JDK-8235989

**Comment by satscoffee** [comment]
It wasn’t voiceover but an accessibility keyboard that let me interact using an on-screen keyboard. I was not using it during the error, but it was enabled and minimized. I disabled the Accessibility Keyboard and Bisq2 works like a charm now. On Aug 23, 2024, at 08:43, HenrikJannsen ***@***.***> wrote:﻿
Do you have anything special enabled/disabled in Accessibility?
Here is a related bug report when using voicover: https://bugs.openjdk.org/browse/JDK-8235989

**Comment by HenrikJannsen** [comment]
Ah good its resolved.
