### ISSUE TITLE
Make autoSlide Togglebox component

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#270]
As we got rid of the JFoenix dependency we need a replacement for the autoSlide Togglebox component.
At first its ok to only have it graphically equvalent, no animations needed. Minimal animations can be added in a second step.
Does not need to be a full JavaFx compliant component but can be a simple higher level composition component.

@xyzmaker123 Interested in that task?

**Comment by xyzmaker123** [comment]
Yes
