### ISSUE TITLE
Add BSQ / USD price when burn or bond event happened

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#2735]
We should take the BSQ value in USD into account for the trade amount limit calculation by reputation score.
We need to get the BSQ price at the burn/bond event delivered by the oracle node.  We should use the 30 days average.

We could consider to use the BSQ in USD value directly for the reputation score calculation. As we use the historical price the score stays static. A problem though is that the price is not deterministic (derived from trade statistics) which would cause different prices from different oracle nodes. We could ignore that by annotating the field with`ExcludeForHash` and accept that there might be slight differences of one's reputation score if multiple oracle nodes got different prices.
There is also a risk that a motivated attacker might try to manipulate the BSQ rate by self trades. We have some outlier detection in the code but it need to be checked how much risk remains. A manipulated BSQ price would have negative consequences for the DAO, so we should not take that risk lightly.

Alternatively we could add a feature to the security manager to publish the 30 day average price to the network once a month. This would cause some manual management work, adds more weight to security manager but would remove the risk for BSQ price manipulation (at lease a significant one, as the security manager might decide to ignore BSQ price changes which looks suspicious).

**Comment by suddenwhipvapor** [comment]
Would implementing an "average bsq price across oracle nodes" be too much of a complication?
Otherwise linking amount limit to bsq price at the moment of the burn, better yet reputation score to the dollar value of the amount burned (which takes care of the former, too), is a useful improvement.

As of now, I fail to understand how a malicious actor would take benefit from manipulating bsq price through self trades, do you mean that a large holder could "sell to himself" to increase the net worth of his stack and so also the reputation score he would obtain from burning?

**Comment by HenrikJannsen** [comment]
I need to look into options how to sync the BSQ between oracles but its likely difficult and problematic.

A scammer could buy e.g. 300 BSQ at price of 600 USD. Then he makes lots of self trades with very high BSQ price, so average price goes up to say 10 BSQ/USD. The he burn the BSQ now having a 5x impact on the trade limits. The BSQ price will take a while until finding is real value. But as we use the burn event price his 5x impact sticks.

**Comment by suddenwhipvapor** [comment]
Oh, much clearer now, and looks like a very possible attack vector, even without taking into account the burning mechanism for bisq2 reputation, as this could disrupt bsq market in general, no?
What I mean is that building resilience against this, is something useful even outside the scope of bisq2 reputation

**Comment by HenrikJannsen** [comment]
The Bisq internal BSQ price cannot be used for security relevant issues as its based on TradeStatistics and those are not verifiable. I don't know any solution to that problem.

**Comment by HenrikJannsen** [comment]
Yes, but as said we have only the data from the tradestatistics and those are not verifiable.

**Comment by suddenwhipvapor** [comment]
30 days average must be used as the metric then, no way around it

**Comment by HenrikJannsen** [comment]
I will drop that for now. To use the BSQ price has too much risks and to add a factor provided by security manager can be added later as well if BSQ price would change a lot.
