### ISSUE TITLE
Change min. required reputation score handling

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#2736]
With the changes for the trade limit and deriving of the limit from the reputation score we have to reconsider the role of the min. required reputation score value.

We could drop the feature completely as we would show a warning anyway for sellers with < 5000 score and others have adjusted trade limits which should provide sufficient security.

**Comment by suddenwhipvapor** [comment]
In the original discussion, I was indeed wondering what the role of the editable minimum repscore value in settings was going to become, once buyers always have the choice to take offers for 25usd no matter that value, and sellers cannot make offers for a larger amount that their reputation allows for, anyway.
If the limitation on the amount is imposed in a hardcoded way on the sellers, yes, that setting on the buyer's side is redundant.
