### ISSUE TITLE
Initialising apiilicationservice failed

### ISSUE THREAD

**Issue by moohuggernini** [bisq-network/bisq2#2820]
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..
[bisq.log](https://github.com/user-attachments/files/16983014/bisq.log)

**Comment by HenrikJannsen** [comment]
You use Version: 2.0.4. Please update to Version: 2.1.0. It has fixed many of those issues.
