### ISSUE TITLE
No more offers in the OfferBook

### ISSUE THREAD

**Issue by akasaka99** [bisq-network/bisq2#2834]
Hi, I use version 2.0.4 on MacOS.
For the last couple of days I do not see any offers at all on any currency in the OfferBook. (See picture attached)
It was working fine before, so I am not sure if I messed up some settings.
Any help would be appreciated.
Many thanks
![Screen Shot 2024-09-17 at 11 11 33](https://github.com/user-attachments/assets/75914466-6a22-4a91-b2a2-7813ccdc09ea)

**Comment by HenrikJannsen** [comment]
Please update to 2.1.0. Everything should work normally
