### ISSUE TITLE
Application notifications

### ISSUE THREAD

**Issue by igorbastosib** [bisq-network/bisq2#2864]
I'm reporting an very annoying behaviour while running on Windows (I don't know about other OS).
Specifically for "Offerbook" I got notified for every single new seller offer, what is annoying. I have favorited X fiat currencies and it would make sense (for me) to get notified only when about those favorited currencies get new offers.
When I wakeup, there are many useless notifications on my Win Notifications panel, quite annoying.

Besides that, all good.

**Comment by HenrikJannsen** [comment]
You can set the notifications per market/channel as well as globally in settings.
