### ISSUE TITLE
Shift+Enter in chat creates 4 new lines

### ISSUE THREAD

**Issue by nostrbuddha** [bisq-network/bisq2#2932]
Bisq version: 2.1.0
OS: Mac OS Sonoma

While in chat (tested in offer book chat, trade chat),
 * typing Enter send the message.
 * typing Shift+Enter is supposed to create a new line. But it creates 3-4 new lines right now.
 
Video attached:

https://github.com/user-attachments/assets/d542d205-39e1-4705-9018-c800aacbe4fb

**Comment by namloan** [comment]
This should be fixed in the next release https://github.com/bisq-network/bisq2/issues/2315
