### ISSUE TITLE
Initialising applicationService failed on Windows

### ISSUE THREAD

**Issue by Mijapi** [bisq-network/bisq2#2955]
When I try to open Bisq 2 on my Windows I am getting the following error:
"An error occured at initializing Bisq:java.util.concurrent.TimeoutException"
I have alos attached the bisq.log file as recommended.

[bisq.log](https://github.com/user-attachments/files/17511701/bisq.log)

**Comment by HenrikJannsen** [comment]
I assume the reason why you closed the issue is that after restart it worked, right?

**Comment by Mijapi** [comment]
Hi, I have realised that I did not use the latest version of Bisq2 when I raised this issue. Since I installed it the problem disappeared.
