### ISSUE TITLE
Problem initialzing Bisq1 & Bisq2

### ISSUE THREAD

**Issue by FlyingRaven0** [bisq-network/bisq2#2973]
Hello,

I haven't used Bisq in a while and already when using it last time several months ago (Version 1) it wouldn't iniitalize completely even after deleting the file (don't remember the name) which was suggested in the forum (it would start from 0% and stopped at 86%).

I discovered Bisq2 today and installed it right away, but unfortunately the same problem persists (stopping at 24%).

I tried already several times always with the same result.

This is the error message

Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.5.4.0-198-generic
Error message:
An error occurred at initializing Bisq: java.util.concurrent.TimeoutException.

I just tried again to run Bisq2 and still the same error persists (stopping at 24%).
Is there anyone who could point out what I can do or if there is already a thread that deals with the same issue?

**Comment by suddenwhipvapor** [comment]
Hello
first of all, is it possible you were using an older version of Bisq1? Up until 1.9.16 the builtin bitcoinj library had an issue with storing the total  blockchain work value, so 1.9.17 is required.
Bisq2 uses Bisq Easy now which is a different trading protocol, so it's not a drop-in replacement for Bisq1.
As of now, latest Bisq2 is 2.1.2.

So there is a chance that updating to latest version for both could solve your issues.

**Comment by FlyingRaven0** [comment]
Thank you very much for that hint!
After updating Bisq 1 the problem was solved.
