### ISSUE TITLE
Make RpcCallFailureException a RuntimeException

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#72]
The `RpcClient` will be called later in `CompletableFuture`s. A checked exception forces us to explicitly handle the exception in the `WalletService`, making the code more complex. A `RuntimeException` can be handled by the caller using `CompletableFuture.handle(...)` or a related method. This allows the `WalletService` consumer to decide how to respond to a failed call. Furthermore, the `WalletService` is not smart enough to handle the exception because it doesn't know the context in which it was triggered.

**Comment by chimp1984** [comment]
Maybe we can discuss a bit the exception handling strategies in context with CompletableFutures at our dev call?
I am often unsure how to deal with it and exception handling can pollute a lot otherwise elegant code and flows.

**Comment by alvasw** [comment]
It's a good idea to discuss it in our next dev call. :+1:
