### ISSUE TITLE
Bounty for adding content for Bisq 2 learn section

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#721]
This is a **bounty task** for a content writer with excellent English language skills to fill our learn sections.

The bounty is paid in BSQ via a Bisq DAO compensation request. Per topic we can offer BSQ worth of **500 USD**. A reference to text authored by the bounty taker would be good to see if the quality and style fits our expectations. 

Proposed topics we want to cover are:
- Bisq
- Bitcoin
- Security
- Privacy
- Wallets
- Open Source (this could be changed to something else as well)

The text should not be too long but refer via hyperlinks to further details if needed. The screenshots show the intended format and length of the content.

 
<img width="1507" alt="Screenshot 2023-04-06 at 12 23 51" src="https://user-images.githubusercontent.com/116298498/230279859-8b4e7407-4252-42cf-a925-303b10096c8e.png">
<img width="1507" alt="Screenshot 2023-04-06 at 12 24 07" src="https://user-images.githubusercontent.com/116298498/230279891-27a89dfb-9dd3-4fad-8f4f-d185b48d4cec.png">

**Comment by niyid** [comment]
Assign?

But I need to know the expected lengths of the articles and due dates.

Regards.

Sample articles:

- https://sites.google.com/site/contagionweb/home
- https://drive.google.com/file/d/1R84wAdMt12n8YMn5E-UKWKEBGrc1s3Jd/view?usp=sharing
- https://drive.google.com/file/d/1eZ46ly39kLv_d4uWiOTwa7-_KSHyc4q4/view?usp=share_link

**Comment by HenrikJannsen** [comment]
There is no hard length defined. The content should give a good overview about the topic and should fit into the screen without scrolling. 

Can you start with one topic and then if delivery satisfies expectations we go on with the next? Maybe Security would be a good one to start.

**Comment by niyid** [comment]
> There is no hard length defined. The content should give a good overview about the topic and should fit into the screen without scrolling.
> 
> Can you start with one topic and then if delivery satisfies expectations we go on with the next? Maybe Security would be a good one to start.

Thanks for the consideration. I am more familiar with other topics of which I would rather write on, and in the following order:

1. Open Source
2. Bitcoin
3. Bisq

**Comment by niyid** [comment]
@HenrikJannsen 

[Open Source (OSS)](https://drive.google.com/file/d/1TDSOQ7_dPaAMyJs1bddXOAWlzOY90alH/view?usp=sharing). 

I await your comments.

**Comment by w0000000t** [comment]
As the author of https://bisq.wiki/Contributor_privacy_and_opsec and https://bisq.community/t/privacy-on-bisq-explained/11243/8 among other articles, I have those to showcase for myself.
I'd like to tackle the privacy and security articles, and while I can no doubt draft a scope for both, I'd like to get some pointers to what is expected to be covered as their main focus, as long as you all think I could be a good author candidate.

**Comment by Jayboi23** [comment]
Hello,

I choose to write on the topic which states BISQ, you can check it [here](https://drive.google.com/file/d/1eiFyWRmionbshDoVAzLx1m5F0vqPhdn7/view?usp=sharing)

**Comment by HenrikJannsen** [comment]
@Jayboi23 
Some comments to your text:
- If the Bisq Multisig trade protocol is explained in Bisq 2 we need to refer to it as a specific protocol as a core feature of Bisq 2 is to support multiple protocols and the initial protocol will be Bisq Easy which is based on reputation.
- The arbitration description is not completely correct. Funds are not released, but the winner of the dispute has the right to get reimbursed either by the refund agent or by the DAO
- The DAO could get more space as its a center piece for Bisq and specially for Bisq 2

**Comment by dugduggler** [comment]
I guess the only thing remaining is wallets, I wrote up a blurb here. 

[Wallets.pdf](https://github.com/bisq-network/bisq2/files/11182493/Wallets.pdf)


First time trying to contribute, any feedback much appreciated!

**Comment by HenrikJannsen** [comment]
> I guess the only thing remaining is wallets, I wrote up a blurb here.
> 
> [Wallets.pdf](https://github.com/bisq-network/bisq2/files/11182493/Wallets.pdf)
> 
> First time trying to contribute, any feedback much appreciated!

I am sorry but I do not consider the text to meet the expectations.

**Comment by HenrikJannsen** [comment]
ChatGPT delivers a very similar text to the one provided by @dugduggler  (not saying it was created by ChatGPT but quality level is about similar and style as well).

I guess I will close that bounty task as failed. The quality of contributions do not satisfy and justify a realtively high payment of 500 USD.

If we use text of one of the contributions we will consider a partial payout.
Please do not propose more samples. We will try another approach.

`
A Bitcoin wallet is a digital wallet that is used to store, send, and receive Bitcoin. It is a software application that interacts with the Bitcoin network, allowing users to manage their Bitcoin assets.

There are two main types of Bitcoin wallets: hot wallets and cold wallets. Hot wallets are connected to the internet and allow for easy access to Bitcoin, but they are less secure and more vulnerable to hacking. Cold wallets, on the other hand, are offline and therefore more secure, but they can be less convenient to use.

Bitcoin wallets can also be categorized by their level of control over the private keys, which are used to access and transfer Bitcoin. Custodial wallets are managed by third-party providers that control the private keys on behalf of the user, while non-custodial wallets give users full control over their private keys.

In addition to storing Bitcoin, some wallets also offer additional features such as the ability to exchange Bitcoin for other cryptocurrencies, and to buy and sell Bitcoin for fiat currencies.

When choosing a Bitcoin wallet, it is important to consider factors such as security, ease of use, and the level of control over the private keys. It is also important to keep in mind that while Bitcoin wallets can provide a high level of security, they are not immune to risks such as hacking, phishing, and loss of private keys.
`

**Comment by dugduggler** [comment]
> ChatGPT delivers a very similar text to the one provided by @dugduggler (not saying it was created by ChatGPT but quality level is about similar and style as well).
> 
> I guess I will close that bounty task as failed. The quality of contributions do not satisfy and justify a realtively high payment of 500 USD.
> 
> If we use text of one of the contributions we will consider a partial payout. Please do not propose more samples. We will try another approach.
> 
> ```
> A Bitcoin wallet is a digital wallet that is used to store, send, and receive Bitcoin. It is a software application that interacts with the Bitcoin network, allowing users to manage their Bitcoin assets.
> 
> There are two main types of Bitcoin wallets: hot wallets and cold wallets. Hot wallets are connected to the internet and allow for easy access to Bitcoin, but they are less secure and more vulnerable to hacking. Cold wallets, on the other hand, are offline and therefore more secure, but they can be less convenient to use.
> 
> Bitcoin wallets can also be categorized by their level of control over the private keys, which are used to access and transfer Bitcoin. Custodial wallets are managed by third-party providers that control the private keys on behalf of the user, while non-custodial wallets give users full control over their private keys.
> 
> In addition to storing Bitcoin, some wallets also offer additional features such as the ability to exchange Bitcoin for other cryptocurrencies, and to buy and sell Bitcoin for fiat currencies.
> 
> When choosing a Bitcoin wallet, it is important to consider factors such as security, ease of use, and the level of control over the private keys. It is also important to keep in mind that while Bitcoin wallets can provide a high level of security, they are not immune to risks such as hacking, phishing, and loss of private keys.
> ```

Thank you for the feedback, I was basing length and content style off of previous posts. I  guess I will lurk a bit more and see what kind of writing style is desired.
