### ISSUE TITLE
Add icons for submenu items when expanded

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#804]
Instead using first character we should use icons:
<img width="97" alt="Screenshot 2023-05-02 at 00 19 05" src="https://user-images.githubusercontent.com/116298498/235495632-260d97e0-bef9-4d56-bc0f-a15097c97165.png">

<img width="259" alt="Screenshot 2023-05-02 at 00 20 25" src="https://user-images.githubusercontent.com/116298498/235495814-de649099-7f13-4bf9-9dd9-72d11cfe56c4.png">

**Comment by darawhelan** [comment]
When menu is collapsed why not hide sub-menu items. Otherwise it would just be a long list of icons.

Users could access the sub menu via the higher menu of which there is already icons that the user is familiar with when menu is expanded.

**Comment by HenrikJannsen** [comment]
> When menu is collapsed why not hide sub-menu items. Otherwise it would just be a long list of icons.
> 
> Users could access the sub menu via the higher menu of which there is already icons that the user is familiar with when menu is expanded.

Hmm... I would prefer to keep the submenu vertical expansion state unchanged if the user changes the horizontal expansion state. Otherwise there is unexpected change (user clicks to collapse horizontally but it would automatically collapse vertically). Also it allows power users who are familiar with the navigation to access all items.
I guess with a smaller icons size maybe with a slightly different gray tone or color would make it sufficiently distinguished from the main menu items.

**Comment by darawhelan** [comment]
Ok, are you able to link to the most recent graphic mock-ups for Bisq 2 so I can have a look. I have looked as past ones but not sure they are up-to-date?

**Comment by HenrikJannsen** [comment]
<img width="1512" alt="Screenshot 2023-05-04 at 00 01 12" src="https://user-images.githubusercontent.com/116298498/235988045-66a4c3bd-6e1d-4023-b10f-1daf9c70d999.png">
<img width="1512" alt="Screenshot 2023-05-04 at 00 01 23" src="https://user-images.githubusercontent.com/116298498/235988090-8f592d91-5b0d-4994-bfe2-85323e313bfa.png">
