### ISSUE TITLE
Gradle: Pass Binary Version Number to Java Code

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#828]
The Electrum/Tor version is set in the `build.gradle` file, and we can pass it to the Java code.

**Comment by HenrikJannsen** [comment]
@rodvar 
Would you want to look into that?
The tor version number could be logged next to the Bisq version at startup and displayed at the network view where we also display version and commit hash.

Electrum version is not needed yet as undecided which wallet will be used.

**Comment by rodvar** [comment]
@HenrikJannsen for sure!

**Comment by rodvar** [comment]
@HenrikJannsen I believe we can close this one
