### ISSUE TITLE
Finish implementation for input validators

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#883]
Input validators are implemented but missing the handling in the UI components to show the error messages and adopt the css.
It should follow the pattern used in JavaFX components/JFoenix.

**Comment by namloan** [comment]
taking a look at this one

**Comment by namloan** [comment]
been offline for a week, I'm retaking this today.

**Comment by HenrikJannsen** [comment]
@namloan Are there still some open? Maybe can can add a bullet point list of the UI screens where validation is open and set priorities to each?

**Comment by namloan** [comment]
@HenrikJannsen we're still missing some validations in 'User options':
* **Reputation**. I started working on this but halted it until https://github.com/bisq-network/bisq2/pull/1320/commits is merged as there will be conflicts. Validating the numbers are >= 0 and that the score isn't calculated when amounts are invalid.
* **Bonded roles**. Not sure what validations we want here but maybe at least text length size.
* **Nodes**. Same as above.

**Comment by HenrikJannsen** [comment]
We can consider the Pro user/contributor sections as lower prio.
Feel free to pause that task and pick anything else with higher prio if you like.

**Comment by HenrikJannsen** [comment]
@namloan Are you still working on that?

**Comment by namloan** [comment]
Nope, it's free. Show we merge with https://github.com/bisq-network/bisq2/issues/1153?
