### ISSUE TITLE
Add validation of data received from the network

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#884]
Before applying data we received from the network we should do a basic validation of the fields. The `fromProto` method is the entry point and it would be good to embed that into the Proto interface to enforce implementation of a validation method.

**Comment by namloan** [comment]
This may need more details about the validations that you're thinking about. Presence of certain fields? Something more complex?

> The fromProto method is the entry point

Is it [NetworkEnvelope.fromProto](https://github.com/bisq-network/bisq2/blob/6d8bce30855bf3ce03ebadd49f584a249f86d59d/network/network/src/main/java/bisq/network/p2p/message/NetworkEnvelope.java#L55)?

**Comment by HenrikJannsen** [comment]
I need to revisit that issue myself. There have been some changes which might make that issue obsolete.

**Comment by djing-chan** [comment]
I can work on that
