### ISSUE TITLE
Do not use String in MaterialPasswordField

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#895]
For security reasons we need to modify `MaterialPasswordField` so that no `String` object gets created for the password.
We should use `CharSequence` instead or the 'bisq.security.SecureString' class and clean up the byte array once the password is not needed anymore. 
The client code must handle it as well accordingly.

String objects could stick around in memory until the GC cleans it up, which is not determined when and if that happen.

**Comment by namloan** [comment]
will tackle this

**Comment by namloan** [comment]
@HenrikJannsen did you already have something in mind for this? It seems like by design JavaFX is only supporting String for text input through TextInputControl. I guess it should be possible to write our own custom input control that uses CharSequence, however it looks like a lot of work so I wanted to double check.

Should this be a feature request to JavaFX instead?

**Comment by HenrikJannsen** [comment]
It it gets too difficult we can postpone it as well. Currently the password protection is only for protecting access to the UI screen and the user db file is encrypted. As long we don't have the wallet the security implications are not that critical.
Also getting access to the application RAM is already a severe breach of a users system. For Bisq 1 we considered it as well but as BitcoinJ holds the private keys as objects in RAM secure password protection would not make the situation better. Bisq 2 has still not yet decided on the lightweight wallet to be used (currently Electrum but we want to check out other alternatives like BDK or Sparrow). So it will also depend on that if that threat scenario is covered by the wallet or not.

**Comment by namloan** [comment]
Thanks for the Sparrow suggestion. Looks like Sparrow hasn't solved the problem either - it's loading the password in a String and converting it to SecureString. A couple of code pointers:

* [LoadWallet.java](https://github.com/sparrowwallet/sparrow/blob/0a469a380bd11424a96214499fd0ced13e213212/src/main/java/com/sparrowwallet/sparrow/terminal/wallet/LoadWallet.java#L71)
* [WalletDialog.java](https://github.com/sparrowwallet/sparrow/blob/0a469a380bd11424a96214499fd0ced13e213212/src/main/java/com/sparrowwallet/sparrow/terminal/wallet/WalletDialog.java#L82)

I can try a similar approach, but the security threat will still remain.

**Comment by HenrikJannsen** [comment]
If we cannot avoid that the entered password gets filled in a java object (String) at the input component level I guess it has no value to try to treat it as secure string further down the road. Just makes code more complex and cumbersome and creates fake sense of security. 
I tend to suggest to drop that as it seems the effort is not worth it and we do not know yet how we can deal with it at the wallet level where it would be much more relevant. 
We can defer it for later when we have decided for the wallet library and see if there is a way to deal with it.

**Comment by HenrikJannsen** [comment]
I marked it as deferred and leave it open. We can revisit it later.

**Comment by HenrikJannsen** [comment]
I think we can drop that as the threat model that an attacker has access to ones memory will not be handled. One is pretty lost anyway if that happens...
