### ISSUE TITLE
Add filter option for offers in public trade chat

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#916]
We should add a filter button with options to filter offers by:
- direction (BUY/SELL/ALL)
- amount range (min-max)
- payment methods
- reputation
- text
- language

The filtered options should be displayed in a box with "chip" buttons which can be removed by clicking the x icon. Similar as we use in payment methods screen for custom methods.

This is not a must have feature for release, but any dev who wants some UI challenge task is welcome to pick it up.

**Comment by HenrikJannsen** [comment]
WIP from https://github.com/bisq-network/bisq2/pull/1156:
<img width="1508" alt="Screenshot 2023-09-05 at 17 38 42" src="https://github.com/bisq-network/bisq2/assets/116298498/3bd6ffea-2641-47bc-a108-f6109d0820be">

We should find a good solution how to add further filter options which will require quite some space. One option is to use a popup with a similar style like the create offer popup. Instead of progress stepper we could use a tab menu for the different filter options. Market can be replaced by language. The search could be also added next to the open filter button if it does not fit well into the popup.

**Comment by HenrikJannsen** [comment]
After further discussion the idea to use a popup was dropped and rather a minimal UI which allows to see the filter changes applied live to the offerbook.

**Comment by djing-chan** [comment]
@axpoems has started to impl. an alternative approach
